### ISSUE TITLE
Lag and crashes with Jedi Survivor - UE4SS_Xinput_v2.5.2

### ISSUE THREAD

**Issue by Vendrean** [UE4SS-RE/RE-UE4SS#114]
**Branch or Release**
UE4SS_Xinput_v2.5.2

**Game and Engine Version**
Jedi Survivor - Unreal4

**Describe the bug**
Lags while playing and random crashes while using Lightsaber Stances mod.
https://www.nexusmods.com/starwarsjedisurvivor/mods/62?tab=posts

I tried disabling all other mods in the mods.txt and disabled the debug gui in the settings. 
It helped with excessive lagging but didn't resolve the issue. 

**To Reproduce**
1. Install Saber Stances mod for Jedi Survivor. 
2. Start game at a point where you have all 5 stances and change around stances via number keys while playing the game.

**Expected behavior**
No lags or crashes. ;)

**Screenshots and UE4SS Log**
[If applicable, add screenshots to help explain your problem, and upload the log.]
(https://pastebin.com/ktYvLdFK)

**Desktop (please complete the following information):**
Win10

**Additional context**

**Comment by Vendrean** [comment]
I furthermore deleted all folders in the mods folder except keybinds, shared and the LightsaberStances. 
I also deleted everything but the "keybinds: 1" line in the mods.txt.

It now works. No clue why because I was just wildly trying around, but no lag and no crashes so far.

**Comment by UE4SS** [comment]
It's not feasible for us to help people with specific mods.
You should contact whoever made the mod and tell them about this problem and if they discover any UE4SS related problems then they can make a new issue.

**Comment by Vendrean** [comment]
The mod creator actually send me here originally. I also posted there of course. 
The mod works fine now though. It seems to have been the other functions causing the problems.
