### ISSUE TITLE
[BUG - Release] Steamdeck Compatability / Input blocking

### ISSUE THREAD

**Issue by Falseflag3** [UE4SS-RE/RE-UE4SS#117]
I am using the version 2.5.2 of UE4SS

**Game and Engine Version**
Jedi survivor with the UE4SS 2.5.2

**Describe the bug**
When installing UE4SS in the game, use a winedlloverride command in the xinput.dll file.
It works fine but the game stops recognizing input from controller buttons, it only responds to keyboard keys, but normally it would be able to use the game's default steam input

**To Reproduce**
1. Launch game
2. Attempt UHT Dump
3. See error in log
4.I looked for any errors in the .log, but even though I am a newbie, I didn't seem to see any errors or conflicts, I can provide the file if asked

**Expected behavior**
I am almost sure that the problem comes from linux or that I need to use another launch parameter perhaps.
People who use windows can use a controller with steam input enabled and working with UE4SS in the game, but in linux (Steam deck) the controller input doesn't work, there must be some conflict I think

**Screenshots and UE4SS Log**
If applicable, add screenshots to help explain your problem, and upload the log. 
I don't have that file right now because I deleted it, but I can regenerate another one if necessary to find the problem

**Desktop (please complete the following information):**
 - OS: [STEAM OS (STEAM DECK)]

**Additional context**
I want to add a mod to the game that needs UE4SS, everything works fine but the problem is that the game stops recognizing controller inputs, I tried using the same steam deck controller and apart from a DualShock via bluetooth, but the game simply doesn't recognize any more inputs command, instead with keyboard keys yes, I would like to get it to work well with command simply.
I know that linux is special and doesn't have much support, but everything works fine except for the little conflict I'm talking about.

**Comment by narknon** [comment]
I came across this thread earlier today https://www.reddit.com/r/HarryPotterGame/comments/11h4v1c/anyone_gotten_ue4ss_working_on_the_steam_deck/jiom3hs/ though I think they mistyped msacm32 as 34.  We don't really plan to add direct steamdeck support any time soon.

**Comment by servel333** [comment]
Is there any known workaround for this issue?

Thanks.

**Comment by UE4SS** [comment]
> Is there any known workaround for this issue?
> 
> The Palworld controls are a mess and there's no way to make a keyboard mapping that behaves like the controller.
> 
> Thanks.

Try an experimental build that uses dwmapi instead if xinput1_3.
Here's a link to the download and instructions: https://github.com/UE4SS-RE/RE-UE4SS/issues/309#issuecomment-1911975127

Other than that, maybe autohotkey could be useful, or a similar program for your particular platform.

**Comment by servel333** [comment]
The new version 3 solves this issue. Renaming the DLL works.
