### ISSUE TITLE
[BUG - Release] FText object value lost in translation

### ISSUE THREAD

**Issue by rolfosian** [UE4SS-RE/RE-UE4SS#129]
**Branch or Release**
v2.5.2

**Game and Engine Version**
Deep Rock Galactic

**Describe the bug**
FText object value lost in translation

**To Reproduce**
1. Launch game
2. Get to Space Rig
3. Run
`local missions = FindAllOf("GeneratedMission")`
`if missions then`
`     for index, mission in pairs(missions) do`
`        local MissionName = mission:GetPropertyValue("MissionName") -- Get FText object`
`        local mtype = MissionName:type()`
`        print(mtype..'\n') -- FText`
`        -- print(MissionName) -- Crashes`
`        print(MissionName:ToString()..'\n') -- Returns Empty`
`    end`
`end`

**Expected behavior**
copy value on the same FText objects in the live view returns _LOCGEN_FORMAT_NAMED(NSLOCTEXT("RandomNames", "RandomNameTemplate", "{FirstName} {LastName}"), "FirstName", NSLOCTEXT("", "97475C1846011FC47E23278153D62F79", "Ruptured"), "LastName", NSLOCTEXT("", "EFA5FE8C4C4FC4A13079669167398F37", "Retreat"))_ - would have expected something similar from ToString(), idk

**Screenshots and UE4SS Log**
If applicable, add screenshots to help explain your problem, and upload the log.

**Desktop (please complete the following information):**
 - OS: Win10

**Additional context**

**Comment by UE4SS** [comment]
The crash appears to be fixed in the 2.XDev branch.
Some of the missions legitimately have empty names but the `FText.ToString` function doesn't return the name correctly because FText is a bit complicated and we haven't properly implemented FText so it will return an empty string even for the missions that do have a name.

**Comment by rolfosian** [comment]
Just tested with 2.xDev build. Still crashing on print(MissionName) with a single standard mission confirmed to have a name. The ones without names are the Deep Dive stages

**Comment by UE4SS** [comment]
This is fixed by b70df3a2eff5545e55014a1cc12277356bff5b9b and 59853220c7350879df22429ab325c91df2b46ea0
