### ISSUE TITLE
Read Access Violation when attempting to load all assets before CXX header dump. (2.0Dev Branch)

### ISSUE THREAD

**Issue by matty45** [UE4SS-RE/RE-UE4SS#13]
Game: Tower Unite
Version: 4.20.3
![devenv_uRjlyHK1X9](https://user-images.githubusercontent.com/17109660/204061670-81520a64-ea57-47b3-b36e-1a3464173a23.png)

Stack Trace:
https://pastebin.com/fJ6GAQRU

[UE4SS.log](https://github.com/UE4SS-RE/RE-UE4SS/files/10096910/UE4SS.log)

**Comment by matty45** [comment]
Crash can be replicated on 1.3.6

**Comment by narknon** [comment]
GMalloc appears to be resolving to an address in the wrong module.  If using a custom GMalloc sig, it may need to be fixed.  Appears to be the same issue for issues #12 and #14 as well.

**Comment by matty45** [comment]
Turns out i was using a outdated settings file, pulled the latest from releases and made sure i was using the latest mods too, repeatedly tried to launch the game without cache until it loads properly, then tried to dump all the assets. Sometimes it fails to load the assets but continues to dump. However most of the time it just crashes.

**Comment by matty45** [comment]
Tried altering MaxMemoryUsageDuringAssetLoading to no avail. i have 16gb ram

**Comment by matty45** [comment]
I think this might be because i dont have enough memory although i have 55% of my ram being used before i start dumping

**Comment by narknon** [comment]
As with #12, not going to focus on a fix for this because the game is online and has PVP.
