### ISSUE TITLE
[BUG - Release] UScriptStruct interactions causing crash

### ISSUE THREAD

**Issue by rolfosian** [UE4SS-RE/RE-UE4SS#136]
**Branch or Release**
v2.5.2

**Game and Engine Version**
Deep Rock Galactic

**Describe the bug**
UScriptStruct interactions causing crash, both with script and with live view mouse input

**To Reproduce**
1. Launch game
2. Get to Space Rig
3. Run
```
local fullname = nil
local dailydeals = FindAllOf('_MENU_Trading_C')
if dailydeals then
    for index, dailydeal in pairs(dailydeals) do
        fullname = string.format("%s",dailydeal:GetFullName())
        if fullname == '_MENU_Trading_C /Game/UI/Menu_Trading/_MENU_Trading.Default___MENU_Trading_C' then goto continue end
        dailydeal = dailydeal:GetPropertyValue('WND_DailyDeal')
        dailydeal = dailydeal:GetPropertyValue('CurrDeal')
        local dtype = dailydeal:type()
        print(dtype) -- UScriptStruct
        -- dailydeal = dailydeal:__index('Resource') -- Crashes
        -- dailydeal = dailydeal:__index('DealType') -- Crashes
        -- dailydeal = dailydeal:__index('ResourceAmount') -- Crashes
        -- dailydeal = dailydeal:__index('Credits') -- Crashes
        -- dailydeal = dailydeal:__index('ChangePercent') -- Crashes

        -- I'm sure these ones aren't anywhere near supposed to be working but I tried anyway to exhaust options and im clueless
        -- dailydeal = dailydeal:__index('CurrDeal') -- Crashes
        -- dailydeal = dailydeal:__index('WND_Trading_DailyDeal_C:CurrDeal') -- Crashes
        -- dailydeal = dailydeal:__index('StructProperty /Game/UI/Menu_Trading/WND_Trading_DailyDeal.WND_Trading_DailyDeal_C:CurrDeal') -- Crashes
        ::continue::
    end
end
```
Crashing in the live view:
1. Launch game
2. Get to Space Rig
3. Search `_MENU_Trading_C `(including the trailing whitespace)
4. Click the non-default one
5. Find `WND_DailyDeal` at the bottom, right click>go to object
6. Go down to `CurrDeal`, click on the drop down for the property in the GUI - around 7 out of 10 times it seems to cause a crash when clicked.

**Expected behavior**
idk

**Screenshots and UE4SS Log**
[If applicable, add screenshots to help explain your problem, and upload the log.](https://cdn.discordapp.com/attachments/1103793090742980718/1122817594940981289/image.png)

**Desktop (please complete the following information):**
Win10

**Additional context**

EDIT:
`dailydeal.Resource`, `dailydeal.ResourceAmount` etc appears to work instead of using `__index()`

**Comment by UE4SS** [comment]
The correct way to use the `__index` metamethod is either of these:
```lua
dailydeal["Resource"]
dailydeal.Resource
```
The usage of `__index` directly as in your code above is not supported.
