### ISSUE TITLE
Access violation attempting to use ue4ss with a 4.27.2 game on injection. (2.0Dev Branch)

### ISSUE THREAD

**Issue by matty45** [UE4SS-RE/RE-UE4SS#14]
Game is Brickadia (free-to-play)

Addresses have all been confirmed to be correct

![devenv_xCMXrxB0Hi](https://user-images.githubusercontent.com/17109660/204105567-e2099767-7eca-4d26-ac3b-e0f6c9efafa8.png)

Callstack: https://pastebin.com/6iWV3sir

[UE4SS.log](https://github.com/UE4SS-RE/RE-UE4SS/files/10096887/UE4SS.log)

**Comment by matty45** [comment]
Crash can be replicated on 1.3.6

**Comment by matty45** [comment]
Managed to somewhat fix part of the issue but am still getting a crash apon injecting.

Callstack: https://pastebin.com/NrrNEabg
[UE4SS.log](https://github.com/UE4SS-RE/RE-UE4SS/files/10117502/UE4SS.log)

**Comment by narknon** [comment]
Game doesn't seem to be available to download currently.
