### ISSUE TITLE
[BUG - Control + o GUI toggle broken]

### ISSUE THREAD

**Issue by Mythical-Github** [UE4SS-RE/RE-UE4SS#164]
**Branch or Release**
2c9847e3b2eac19a97608e223af96485f12308fc

**Game and Engine Version**
EscapeTheBackrooms UE 4.27

**Describe the bug**
When pressing Control + o to close just the giu, it also crashes the game
this happens when the console is set to visible on startup, as well as not

**To Reproduce**
Install the commit above to escapethebackrooms and try the control + o combo to toggle gui

**Expected behavior**
GUI actually toggles

**OS**
Windows 10

**Comment by Mythical-Github** [comment]
b757075434fc4af245f8433fb518874e649b8088

With this commit
now both open and close gui crash the game
instead of just close gui

**Comment by UE4SS** [comment]
> [b757075](https://github.com/UE4SS-RE/RE-UE4SS/commit/b757075434fc4af245f8433fb518874e649b8088)
> 
> With this commit now both open and close gui crash the game instead of just close gui

I'm having difficulties reproducing this problem.

**Comment by Mythical-Github** [comment]
517450125bbe6ff9f745c7aa70617d4ae0ec6f35

this commit fixed the issue and now open and load work perfectly

**Comment by UE4SS** [comment]
Hmm.
I'm unsure why that commit would fix this.
Taking a reference to `this` in the `stop_gui` lambda shouldn't cause any problems, and we're doing that anyway for the lambda passed to `TRY`.
