### ISSUE TITLE
Creating a C++ mod

### ISSUE THREAD

**Issue by sinaflair** [UE4SS-RE/RE-UE4SS#166]
Hi, i have been following this tutorial https://docs.ue4ss.com/dev/guides/creating-a-c%2B%2B-mod.html on creating c++ mod, at the end it says to build the project but after that it does not mention the next steps

**Comment by UE4SS** [comment]
The current directory structure for C++ mods is: `Mods/<ModName>/dlls/main.dll`.
As long as that file exists, and it's enabled in mods.txt, an attempt to load it will be made.
Please close this issue if this answers your question.

**Comment by sinaflair** [comment]
Yep thank you
