### ISSUE TITLE
[BUG - Release] Tried to execute UFunction::FuncPtr hook but there was no function map entry for UFunction:

### ISSUE THREAD

**Issue by Dastano** [UE4SS-RE/RE-UE4SS#167]
Hey, not entirely sure if this is a bug or if there is a way around. But I got a Blueprint Function (at last I can call it inside UE Editor)

It is part of the Game's BlueprintLibrary, a compilation of a lot of functions, for quick access.

However, hooking any Function of it, creates this Error. I am curious, if it could be, because the Name is too long?
I wasn't able to test it with a C++ Mod yet, since I have no clue, how to port the Code over to C++.

It works fine on other functions, that are not part of this Library. 

**Branch or Release**
Latest Github Version

**Game and Engine Version**
5.1.1/5.2

**Describe the bug**
`RegisterHook("/Script/Game.GameBlueprintFunctionLibrary:isShipping", function()
    return true
    end)
    `
Creating the following hook and calling the Function afterward returns:

`[10:42:37] Mod button TestHook hit.
[10:42:37] Tried to execute UFunction::FuncPtr hook, but there was no function map entry for UFunction:
        0000000000000000 None.
        No original function to execute.
        Executing ProcessInternal instead.
[10:42:37] Object_ExecuteUbergraph: 0x2709c9d0b00
[10:42:37] ProcessInternal: 0x7ff7de633b00`

**To Reproduce**
1. Launch game
2. Create Hook with LUA Hotkey or on main.lua
3. See error in log

**Expected behavior**
Overwrite the Functions' outcome to be true.

**Desktop (please complete the following information):**
Win11

**Comment by narknon** [comment]
Not able to assist with specific game functions, particularly those that try to change the game release mode.
