### ISSUE TITLE
hogwart legacy c++ mod

### ISSUE THREAD

**Issue by sinaflair** [UE4SS-RE/RE-UE4SS#173]
Hi, I'm following this tutorial https://docs.ue4ss.com/dev/guides/creating-a-c%2B%2B-mod.html , i'm using this version 2.5.2 and the game is hogwarts legacy, after following all the steps the gui does not open, the gui used to open when i used xinput v2.5.1 but then if i tried to make the mod with v2.5.1 i would get the below error after this step cmake -S . -B Output, i dont get this error when i use v2.5.2, so i tried using v2.5.2 to make the mod with v2.5.1 xinput but it was giving not able to install mod error in the gui probably cause i used different versions.

-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.22621.
-- The C compiler identification is MSVC 19.36.32537.0
-- The CXX compiler identification is MSVC 19.36.32537.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
IPO - Supported: YES;
Project: UE4SS
Unknown build type. (Build type: )
Project: File (STATIC)
Project: DynamicOutput (STATIC)
Project: Function (HEADER-ONLY)
Project: Constructs (HEADER-ONLY)
Project: Helpers (HEADER-ONLY)
Project: SinglePassSigScanner (STATIC)
CMake Deprecation Warning at RE-UE4SS/Dependencies/zydis/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Deprecation Warning at RE-UE4SS/Dependencies/zydis/dependencies/zycore/CMakeLists.txt:5 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Failed
-- Performing Test COMPILER_HAS_DEPRECATED
-- Performing Test COMPILER_HAS_DEPRECATED - Success
Project: ASMHelper (STATIC)
** AsmJit Summary **
   ASMJIT_DIR=C:/Users/akshi/Downloads/MyMods/RE-UE4SS/Dependencies/PolyHook_2_0/asmjit
   ASMJIT_TEST=FALSE
   ASMJIT_TARGET_TYPE=STATIC
   ASMJIT_DEPS=
   ASMJIT_LIBS=asmjit
   ASMJIT_CFLAGS=-DASMJIT_STATIC
   ASMJIT_PRIVATE_CFLAGS=-MP;-GF;-Zc:inline;-Zc:strictStrings;-Zc:threadSafeInit-;-W4;-DASMJIT_STATIC
   ASMJIT_PRIVATE_CFLAGS_DBG=-GS
   ASMJIT_PRIVATE_CFLAGS_REL=-GS-;-O2;-Oi
Project: Unreal (STATIC)
Project: MProgram (HEADER-ONLY)
Project: Input (STATIC)
Project: LuaRaw (STATIC)
Project: LuaMadeSimple (STATIC)
Project: FunctionTimer (STATIC)
Project: ScopedTimer (HEADER-ONLY)
-- Module support is disabled.
-- Version: 9.1.1
-- Build type:
-- CXX_STANDARD: 23
-- Required features: cxx_variadic_templates
Project: ParserBase (STATIC)
Project: IniParser (STATIC)
Project: JSON (STATIC)
Project: ArgsParser (STATIC)
Project: LuaWrapperGenerator (STATIC)
[LuaWrapperGenerator] LLVM_PATH: D:\LLVM\14.0.6\llvm+clang-14.0.6-x86_64-windows-msvc-release-mt
UE4SS
Major: 2, Minor: 5, Hotfix: 0, PreRelease: 0, Beta: 0
-- The ASM_MASM compiler identification is MSVC
-- Found assembler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/ml64.exe
-- Configuring done (6.1s)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
C:/Users/akshi/Downloads/MyMods/RE-UE4SS/Dependencies/PolyHook_2_0/ZYCORE_INCLUDE_DIR
   used as include directory in directory C:/Users/akshi/Downloads/MyMods/RE-UE4SS/Dependencies/PolyHook_2_0
C:/Users/akshi/Downloads/MyMods/RE-UE4SS/Dependencies/PolyHook_2_0/ZYDIS_INCLUDE_DIR
   used as include directory in directory C:/Users/akshi/Downloads/MyMods/RE-UE4SS/Dependencies/PolyHook_2_0

CMake Error: install(EXPORT "PolyHook_2-targets" ...) includes target "PolyHook_2" which requires target "Zydis" that is not in any export set.
CMake Error: install(EXPORT "PolyHook_2-targets" ...) includes target "PolyHook_2" which requires target "Zycore" that is not in any export set.
-- Generating done (0.2s)
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by narknon** [comment]
2.5.1 did not have c++ mods.  The GUI is off by default, turn it on in settings.

**Comment by sinaflair** [comment]
Thanks! Now i can see the gui but i can't see any message saying MyAwesomeMod enabled or the output log message Output::send<LogLevel::Verbose>(STR("MyAwesomeMod says hello\n")); , while following step 2 in part 4 it mention this file UE4SS-cppsdk_xinput.dll present in this folder MyMods\Output\ue4ss\Binaries\x64\Release , there is no UE4SS-cppsdk_xinput.dll in that folder but there is UE4SS-cppsdk.dll , xinput1_3.dll and ue4ss.dll so i've been moving UE4SS-cppsdk.dll directly as it seems to have been renamed already.

**Comment by narknon** [comment]
Right click on the cppsdk_xinput in the solution and build it, and make sure you build xinput too

**Comment by sinaflair** [comment]
okay this time it creates UE4SS-cppsdk_xinput.dll , i renamed it to UE4SS-cppsdk.dll and placed in the folder but it the output isn't being displayed or MyAwesomeMod enabled message is not appearing in the console
