### ISSUE TITLE
[BUG - Release] xinput.dll no longer working with controllers.

### ISSUE THREAD

**Issue by JaredWeakStrike** [UE4SS-RE/RE-UE4SS#179]
**Branch or Release**
The Tag for the Release you are using, or the commit you used if you built from source yourself.
fb54e3a for the the source build and release xinput 2.5.2

**Game and Engine Version**
Game where the bug occurred, and the UE engine version of the game.
Game: Octopath Traveler 2 
UE Engine: 4.2.7

**Describe the bug**
When using release xinput 2.5.2 the game reads controller input just fine. 
However, when using source it hooks into the game fine but it doesnt read controller input anymore.

**Expected behavior**
I expected the controller to work since it worked on an older version.

**Screenshots and UE4SS Log**
If applicable, add screenshots to help explain your problem, and upload the log.

**Desktop (please complete the following information):**
 Windows 10

**Additional context**
I am using a dual shock 4

**Comment by JaredWeakStrike** [comment]
It was a setup issue.

**Comment by WistfulHopes** [comment]
What was the issue? I am also having this issue with another game.
