### ISSUE TITLE
[BUG - Master] Compiling project produces error C3861

### ISSUE THREAD

**Issue by Buckminsterfullerene02** [UE4SS-RE/RE-UE4SS#194]
Making this issue on behalf of someone who said they would but keeps forgetting to, while the issue itself is being missed over and over again in the ue4ss discussion channels.

**Branch or Release**
Master branch

**Describe the bug**
During compilation, the following error has occured for 3 users:
```
C:\Users\wasikuss\gitrepos\RE-UE4SS\Dependencies\Unreal\src\UnrealCrc32.cpp(382): error C3861: '_byteswap_ulong': identifier not found
C:\Users\wasikuss\gitrepos\RE-UE4SS\Dependencies\Unreal\src\UnrealCrc32.cpp(421): error C3861: '_byteswap_ulong': identifier not found
```

**To Reproduce**
1. Fresh clone the repo
2. Attempt to compile
3. See error in log

**Current workaround**
Fixed localy by adding `#include <stdlib.h>` to the `UnrealCrc32.hpp` file.

**Comment by UE4SS** [comment]
Should be fixed by cd522b683d49e5ff484afc5c07462dc50cae7333
