### ISSUE TITLE
"Cppsdk not present, cpp mods will not be loaded" - what's it mean?

### ISSUE THREAD

**Issue by RedFlames** [UE4SS-RE/RE-UE4SS#200]
**Branch or Release**
v2.5.2

**Game and Engine Version**
Pseudoregalia, uses UE 5.1

**Describe the bug**
In the console, it says "Cppsdk not present, cpp mods will not be loaded" if I don't have "Mods/ue4ss-cppsdk.dll" present, and yet it loads my Cpp mod. It is entirely unclear to me what this means.

Plus it only works with the xinput1_3.dll that I built in my Cpp project, so would I have to distribute this with a potential mod?

**To Reproduce**
1. Follow the steps to making a C++ mod
2. (Bonus step: learn that I can't clone main, need to checkout tag v2.5.2, and then apply #194 workaround)
3. Copy dll of my new mod to its folder in Mods
4. if I use the v2.5.2 official release xinput DLL, I get a fatal error
5. if I use the xinput1_3.dll built from my MSVC project, I still get the ominous "Cppsdk not present" message and yet my mod prints to console
6. if I then copy cppsdk_xinput.dll from my MSVC build output to Mods/ue4ss-cppsdk.dll the message goes away

**Expected behavior**
I'm really just not sure what I'm supposed to do, and I'd like to know
1. Can I get my C++ mod to work with the official v2.5.2 release?
2. What difference does it make if I put Mods/ue4ss-cppsdk.dll in place, if my mod loads either way?

**Screenshots and UE4SS Log**

![image](https://github.com/UE4SS-RE/RE-UE4SS/assets/1682215/420b4b47-3af2-4dcf-851e-e833ca2795b5)

I could provide more logs from CMake and MSVC but I'm not actually having any build issues currently besides #194 workaround

**Desktop (please complete the following information):**
 - OS: Win10

**Additional context**
meow 🐈

**Comment by localcc** [comment]
You should not be linking with xinput1_3, instead link to cppsdk and then the mod will require it. Linking to cppsdk is more portable as it allows multiple injection methods of ue4ss rather than just xinput

**Comment by RedFlames** [comment]
Oh right, I forgot I edited my mod CmakeLists.txt to say
```
target_link_libraries(${TARGET} PUBLIC xinput1_3)
```
on v2.5.2 would I change this to cppsdk, or ue4ss? Since in the current main branch the cppsdk and xinput1_3 targets seem to have gone away, but I think on 2.5.2 I still got them.

Also I built my mod as Release instead of Debug and it seems to load with official release, which I guess makes sense 🙃

**Comment by UE4SS** [comment]
> Oh right, I forgot I edited my mod CmakeLists.txt to say
> 
> ```
> target_link_libraries(${TARGET} PUBLIC xinput1_3)
> ```
> 
> on v2.5.2 would I change this to cppsdk, or ue4ss? Since in the current main branch the cppsdk and xinput1_3 targets seem to have gone away, but I think on 2.5.2 I still got them.
> 
> Also I built my mod as Release instead of Debug and it seems to load with official release, which I guess makes sense 🙃
> 
> Edit:
> 
> Looks like it would be against ue4ss. But then I am back to
> 
> ```
> [12:38:51] Failed to load dll <[...]\Binaries\Win64\Mods\MyModYeah\dlls\main.dll> for mod MyModYeah, error code: 0x7e
> [12:38:51] Was unable to install mod 'MyModYeah' for unknown reasons. Mod is not installable.
> ```
> 
> (getting this even with the xinput1_3.dll that was built in my project solution and with ue4ss-cppsdk.dll in place)
Make sure you're building your mod with the exact same version of UE4SS that you've installed in your game directory.
This includes building both in the same build mode, meaning both in Release or both in Debug.
