### ISSUE TITLE
[BUG - 2.x (852c937)]

### ISSUE THREAD

**Issue by littlemeowmeow0134** [UE4SS-RE/RE-UE4SS#215]
**Branch or Release**
Commit 852c937

**Game and Engine Version**
Pseudoregalia, 5.1

**Describe the bug**
In C++ mods, Hook::RegisterProcessConsoleExecCallback does not actually register a hook on Proton or Wine. It works fine on Windows.

**To Reproduce**
1. Launch game with C++ mod which uses Hook::RegisterProcessConsoleExecCallback
2. Enter console commands with the ConsoleEnabler lua mod, no callback is run

**Desktop (please complete the following information):**
 - OS: Linux Mint, Proton Experimental, Wine 8.0.2

**Comment by UE4SS** [comment]
Fixed by https://github.com/Re-UE4SS/UEPseudo/commit/970770a25130b2f3c36626d430a67308b5c1a858
