### ISSUE TITLE
[BUG - Release]  2.5.2 Not fully dumping CXXHeader

### ISSUE THREAD

**Issue by altefwan** [UE4SS-RE/RE-UE4SS#235]
**Branch or Release**
2.5.2

**Game and Engine Version**
Kingdoms Reborn, UE v4.25.4.0

**Describe the bug**
I was able to successfully dump the CXXHeaders of the game but it doesn't seem to contain objects and functions pertaining to game logic and only contains the UI. The game came with a pdb so I loaded it in IDA and was able to see objects and functions that weren't present in the CXXHeaderDump. I also wasn't able to see it in Live View.

**To Reproduce**
1. Launch game
2. Make CXX Dump
3. Open game in IDA
4. Load PDB
5. Compare dump with IDA

**Expected behavior**
CXXHeaderDump containing objects and functions of both UI and game logic.

**Desktop (please complete the following information):**
 - OS: Win10

**Comment by UE4SS** [comment]
We can only dump objects and functions that have been reflected, meaning the game devs must use the appropriate UE macros.
If they choose not to use those macros, then there's no information for us to dump.
The PDB file contains all functions (and more) from the game so it makes sense that you're finding functions in there that don't exist in our dumps.

**Comment by altefwan** [comment]
Thank you. I also tried another dumper and the result was the same. I kind of figured it out but I guess I was hoping for everything to work out because I was excited to use the built in lua mod maker. Thank again.
