### ISSUE TITLE
[Feature] Support games with encrypted GName and UObject pointers

### ISSUE THREAD

**Issue by mstan** [UE4SS-RE/RE-UE4SS#237]
Hi,

I am currently on a project for a game on Unreal 4.27. In working with a developer for another tool, I learned that the particular game I am working on specifically encrypts the pointers themselves. 

I have a copy of the other tool that is able to successfully dump an MDK of the game. Unfortunately, I'm not the most well versed in C++ so I don't know that I could easily articulate the specifics of what was changed. I'm happy to spend some time with a dev to pick this up, if there's interest.

**Comment by narknon** [comment]
We intentionally do not support this as this is not a tool designed for games with competitive online gameplay, which is normally when these measures would be taken. If the game is end of life with servers going out of service or actually not competitive then a specific build for the game could be discussed.

**Comment by mstan** [comment]
Hi @narknon . You are correct, the game is an online competitive shooter. The game is, however, nearing its end of service at the end of November. The initiative I am working on reverse engineer it in an effort to enable private servers following end of service.

I already have a private cooridinator service mostly functional from mitmproxy packet sniffing. I also am aware that game client has bundled server code assets and I'm able to invoke the server behavior and get clients to connect. However, some of the game state and server/cooridinator behavior I'm struggling with at the moment as I'm not able to capture data between the game servers <> cooridinator as the developer never self-hosting available.

I'm happy to share a tech demo of what I have thus far if there's interest.

**Comment by narknon** [comment]
By an chance does it involve mechas?

**Comment by mstan** [comment]
> By an chance does it involve mechas?

Nailed it.

**Comment by narknon** [comment]
Join the server and send me a dm.
