### ISSUE TITLE
[Bug] Invalid Regex searches causing crashes

### ISSUE THREAD

**Issue by narknon** [UE4SS-RE/RE-UE4SS#238]
Regex search crashes if you use certain characters or invalid syntax.  For example, an escape character '\\' with nothing following it.

**Comment by UE4SS** [comment]
Fixed by 16cb35af458e25cfbb5561cf614b2688e07cc99c

**Comment by UE4SS** [comment]
It will output an error in the console if the regex is invalid and then it will abort the search.
