### ISSUE TITLE
[BUG - All] UEGenerator::generate_enum_value_definitions generating _MAX entry when it shouldn't

### ISSUE THREAD

**Issue by UE4SS** [UE4SS-RE/RE-UE4SS#282]
**Branch or Release**
All

**Game and Engine Version**
N/A

**Describe the bug**
The function `UEGenerator::generate_enum_value_definitions` generates the `_MAX` entry even when the original enum doesn't have such an entry.
This can cause the error `Redefinition of enumerator`.
UE (`Engine/Classes/Materials/MaterialExpressionDataDrivenShaderPlatformInfoSwitch.h`):
```c++
enum EDataDrivenShaderPlatformInfoCondition : int
{
	COND_True
	COND_False
};
```
UEGenerator::generate_enum_value_definitions:
```c++
enum EDataDrivenShaderPlatformInfoCondition
{
    COND_True,
    COND_False,
    COND_Max,
};
```

**To Reproduce**
N/A

**Expected behavior**
UEGenerator::generate_enum_value_definitions should probably only generate `_MAX` if this entry actually exists in the enum, or at least there should be an option for this behavior.

**Screenshots and UE4SS Log**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by Buckminsterfullerene02** [comment]
Fixed in #291
