### ISSUE TITLE
A PR might've been accidentally undone, causing a crash on startup.

### ISSUE THREAD

**Issue by MostlyBored** [UE4SS-RE/RE-UE4SS#3]
It looks like pull request 0cf0696725b8c1628eae160a056f7ed83fc4662d got undone by 1d082e8ead698b2ff587323c1203c9a18678f898.

It doesn't seem like the corresponding change in the LuaMadeSimple submodule was reverted which leads me to believe that this was an accident.

Either way, there's now a crash on startup in `FName::construct` when it calls `lua.transfer_stack_object`.

**Comment by nReCon** [comment]
Note that commit f6f0e7b5d7c8802c063958a522c8416addc86ccb didn't fix this.
That commit only brought in the changes partially.

**Comment by MostlyBored** [comment]
This appears to have been fixed in the 2.0Dev branch by f6f0e7b5d7c8802c063958a522c8416addc86ccb.
