### ISSUE TITLE
[BUG - Release] Palworld still crashes when loading save..

### ISSUE THREAD

**Issue by W1nKille3r** [UE4SS-RE/RE-UE4SS#312]
https://github.com/UE4SS-RE/RE-UE4SS/issues/309#issue-2102095972

**Branch or Release**
Experemental Branch (xinput)

**Game and Engine Version**
- Palworld 0.1.3.0
- Unreal Engine 5

**Describe the bug**
Game crashes anyways when there no mods installed

In previous crashing - game didn't even initialize mods. Crashing on loading process.
This time, world is kinda loads, you hear location jingle. But game still crashes. And seems like there no clear description what cause this.

Its dumb when game let you play in one session after creating world. And doesn't let you launch it second time.

**To Reproduce**
1. Launch game
2. Load save
3. Game crash

**Expected behavior**
Game doesn't crash with UE4SS

**Desktop (please complete the following information):**
 - OS: Win10

**Comment by UE4SS** [comment]
Can you clarify if this is with all mods disabled ? Is [this comment](https://github.com/UE4SS-RE/RE-UE4SS/issues/309#issuecomment-1912158724) still accurate ?

Also, your link at the top of this issue just goes to here.

**Comment by MoRanYue** [comment]
you may edit UE4SS's configuration file, set bUObjectCache to false

**Comment by W1nKille3r** [comment]
Sorry for long response, I wasn't in the mood to deal with the game.
I'll write a solution that worked for me

Find **UE4SS-settings.ini**
Go to string: `GuiConsoleEnabled = 1`
Change it to **"0"** (without quotation marks)

Then game will stop crashing with no reason.
Gonna hope i will never encounter this bug where I have to ping a developer for no good reason.

**Comment by Sylus1000** [comment]
I made a tool for anyone struggling with installing these mods here:
https://github.com/Sylus1000/PalWorldUE4SSModLoader/releases/tag/v1.0
