### ISSUE TITLE
Keyboard Binding Settings

### ISSUE THREAD

**Issue by 9192jks** [UE4SS-RE/RE-UE4SS#318]
Hello, I'm using the program well. But while using Palwold for mode, there are many cases where the "INS" key is set among many other modes
I'd like to change the key settings.
Is there a function to change it to a key other than the "INS" key?
Please understand that there may be mistranslation or translation using a Google translator because I am not good at English.

**Comment by UE4SS** [comment]
The only thing we use the `INS` key for is to manually load BP mods.
This can be changed at the bottom of `Mods/BPModLoaderMod/Scripts/main.lua`.
See the bottom of `Mods/Keybinds/Scripts/main.lua` for all possible keys.

If you're using any third-party mods, you should search all their `.lua` files for `RegisterKeyBind`.

**Comment by 9192jks** [comment]
Thank you for your kind reply. Have a nice day
