### ISSUE TITLE
[BUG - Release] Mods not loading if client is connected to a server (co-op)

### ISSUE THREAD

**Issue by Dekita** [UE4SS-RE/RE-UE4SS#319]
**Release 2.5.2**
**Palworld, UE5.1, PalworldModdingKit**
Palworld doesnt reload the game state when the player connects to a game server. This results in "mods not working". Some users are also reporting an issue being unable to use the insert key to force reload mods. 

I tried to make an edit to the ue4ss bpmodloader mod, to allow for blueprint logic mods to work when a client is playing on servers:

```lua
-- RegisterInitGameStatePostHook(function(ContextParam)
--     LoadMods(ContextParam:get())
-- end)
RegisterHook("/Script/Engine.PlayerController:ClientRestart", function(self, NewPawn)
    LoadMods(UEHelpers.GetWorld())
end)
```
Thats what i edited out, and what i replaced it with. this works completely fine for fixing the issue mentioned above, but it creates a new issue, of the console being spammed with "Not valid or not player controlled" when the player tries to get on/off a mount... its like, 3-5 seconds as well.. the entire everything freezes while the log spams the message. 

Hoping for a fix or a better solution for my edit that will keep the functionality of reloading mods when a client connects to a server, as well as not causing the game to freeze when the player gets on a mount?

**Steps to reproduce the behavior:**
- configure ue4ss and add some logic mods to game
- launch game
- connect to single player
- see mods working as expected
- return to title (or reload game fresh)
- connect to multiplayer/dedicated server
- see mods not working / see lag when dis/mounting (if using the edit to bpmodloadermod from above)

**Expected behavior:**
Logic mods should be properly reloaded when the player enters a server world, as it is when they enter single player.. 

**Desktop:**
Win10, Ryzen 5600x, 3070ti,

**Comment by UE4SS** [comment]
We should not support using mods on a server, instead, we should stick to single-player mods only.

**Comment by localcc** [comment]
Games which use coop multiplayer, or dedicated servers for non competitive games benefit from mods. I think we should consider this as a genuine issue and reopen it.

**Comment by UE4SS** [comment]
> Games which use coop multiplayer, or dedicated servers for non competitive games benefit from mods. I think we should consider this as a genuine issue and reopen it.

Oh my bad, I thought this game had a non-coop multiplayer component.

**Comment by tokyubevoxelverse** [comment]
this is reproducing as of 1.0.1.100619 on crossplay PC servers and any sort of multiplayer servers or dedicated servers/community servers for my users using my mod PalVariety2026 on steam workshop. any new insights on to this, i come from the Forza community, not sure if i am doing something wrong in my mod's update? i added a bunch to the paldex entries, ppl didnt like that so im removing them. however i doubt these changes cause the "connection to server lost" errors, especially when both parties have the pak they need. but worth noting its heavily reproducible and it worked fine on multiplayer servers during my initial launch, before the 619 patch, and after 1.0 launch.

**Comment by tokyubevoxelverse** [comment]
ive fixed this issue. ignore me. this was user error and not a bug.
