### ISSUE TITLE
To maintainers: Remember the GH action for the next release

### ISSUE THREAD

**Issue by UE4SS** [UE4SS-RE/RE-UE4SS#329]
Please remember to use the github release action for this, because there's the whole docs situation which won't be resolved if you manually create a release.

I'm talking about the fact that the docs are supposed to have different versions for each UE4SS version and that it currently doesn't because we have never run the action.
Once the action has been run, there's supposed to be two docs versions, one for whatever is the next version (meaning it'll be the current version at that point), and one for dev, and the dev docs will effectively correspond to the main branch.

**Comment by Buckminsterfullerene02** [comment]
Thanks a lot for the reminder. 

We have delayed the release for tomorrow as a bug with manually setting engine version in config file has been found with pattensleuth and obviously we don't want to rush into this.
