### ISSUE TITLE
[BUG - Release] LoadAsset and RegisterHook problems

### ISSUE THREAD

**Issue by jozhn** [UE4SS-RE/RE-UE4SS#354]
**Branch or Release**
Releases 3.0.0

**Game and Engine Version**
UE5.1.1

**Describe the bug**
1. LoadAsset
I cannot load Actors or Widget Blueprints by `LoadAsset` with long asset paths.
Such as:
```lua
LoadAsset("/Game/Mods/MiniMap/WBP_MiniMap.WBP_MiniMap_C")
```
The return value is not valid. However, it works for textures.

2. RegisterHook
This function doesn't work when I try to hook native ufunction or blueprintimplementableevent ufunction on a blueprint object.
Such as:
```lua
RegisterHook("/Game/Mods/MiniMap/ModActor.ModActor_C:ReceiveBeginPlay", function (ModActor)
        print("MiniMap ModActor created!", ModActor:GetFullName())
    end)
```
It only works for ufunctions defined in blueprints when trying to hook a blueprint object.

**To Reproduce**
1. Write lua code like above
2. Launch game

**Expected behavior**
LoadAsset could work for actors and blueprints.
RegisterHook could work for ufunctions in blueprint objects.

**Comment by UE4SS** [comment]
I'm currently unsure about `LoadAsset`.

When you say `RegisterHook` doesn't work, what exactly happens ?
Is there some kind of error, and if so, what ? Or does it fail silently ?
One thing to note is that if the function hasn't been used in your mod BP (even if it exists but does nothing), it will effectively be optimized out by UE and is thus never called and is never picked up by RegisterHook.

**Comment by nexustheru** [comment]
unreal dont like long paths, and operative system is a hell with path and short cuts, try use combine string ,and  odten slashes is an issue. u might need 2, or the other way like // or \\ or in brackets etc , fire up unreal engine and try there. if its ok there then it cant complain when program is launching.

**Comment by jozhn** [comment]
> I'm currently unsure about `LoadAsset`.
> 
> When you say `RegisterHook` doesn't work, what exactly happens ? Is there some kind of error, and if so, what ? Or does it fail silently ? One thing to note is that if the function hasn't been used in your mod BP (even if it exists but does nothing), it will effectively be optimized out by UE and is thus never called and is never picked up by RegisterHook.

I cannot load widgetblueprint in my pak by `LoadAsset` but I works when I try to load wbp from the game pak. It's weird.

When I use `RegisterHook` to hook a ufunction from a blueprint class such as `ModActor`, It works only when the ufunction is defined in the bp(non-native). But I want to hook functions defined in its parent c++ class `AActor`. So I can just hook all Actors and judge the name or class of the actor. The performance is bad. Maybe we can optimize this way?

**Comment by jozhn** [comment]
> > When I use `RegisterHook` to hook a ufunction from a blueprint class such as `ModActor`, It works only when the ufunction is defined in the bp(non-native). But I want to hook functions defined in its parent c++ class `AActor`. So I can just hook all Actors and judge the name or class of the actor. The performance is bad. Maybe we can optimize this way?
> 
> You will need to show your code. I don't know what function you're talking about or what exactly you're doing in the hook so I can't look into why performance might be bad.

Sorry. Now I know why it's not working. The UFunction of blueprintclass must already exist in memory when using `RegisterHook`. I should use `NotifyOnNewObject` first.
