### ISSUE TITLE
[BUG - Release] minor issue since we got logtext but the othe opengl window dont work

### ISSUE THREAD

**Issue by nexustheru** [UE4SS-RE/RE-UE4SS#361]
**Branch or Release**
The Tag for the Release you are using, or the commit you used if you built from source yourself.
main branch newest ,3

**Game and Engine Version**
Game where the bug occurred, and the UE engine version of the game.
4.27.2 

**Describe the bug**
well, the debug windows is not working, its all white, and i had to make my own debug report to get it printet, theres an issue with  vertex shader 150 of imgue.

**Mods directory**
A zip of your Mods folder if you've installed any mods that don't come with UE4SS by default
also the guide making c++ mods is not accurate, u dont get the correct actor. so i did hook on instead wich works. i am attaching my code instead its just one file , feeling out the c++ what it can do, but bug live or bug at any way window is not happening with latest release. https://paste.ofcode.org/KEcB84dujpRrLCGgs2xT5S
https://github.com/nexustheru/myawsomemod/tree/main

**To Reproduce**
1. Launch game
2. Attempt UHT Dump
3. impossible bc windows its all white, and clicking ctrl-0 o or whatever new hotkey, it crashes the game
4. See error in log

**Expected behavior**
to find the source of why text is not appearing on the debug window

**Screenshots and UE4SS Log**
If applicable, add screenshots to help explain your problem, and upload the log.
https://paste.pics/4893701f95dc6b5cd4dfc75bdccfe0f7

**Desktop (please complete the following information):**
 - OS: [e.g. Win10, Win11] win 10

**Additional context**
i tried this code on a slate console window, its fine and works, but as soon as i moved this code into ue4ss main repo as cpp++ mod with source  from deps, we have this issue.

**Comment by UE4SS** [comment]
Is this a new problem in 3.0 ?

**Comment by nexustheru** [comment]
version before i could see the gui error message, now its all blank, as i sayed i had to attach my own stuff to get the error out since it was all blank could not even get headers out, no button nothing., theres an issue with imgue how it renders on the gui part on developer window. prolly minor .  imma tinker around abit more with ue4ss ,theres prolly just a typo

**Comment by UE4SS** [comment]
I have no idea how rendering your own ImGui window will work or how it may or may not interfere with the UE4SS window so unfortunately I can't really help with this problem.
The best I can offer is a quick search: https://stackoverflow.com/a/72901890
Hopefully someone else can help.

What are you planning on using your window for ? If it's for debugging purposes, you can create a tab in our own ImGui window instead of making your own window.

**Comment by nexustheru** [comment]
orginally i wanted to make a cpp mod, but i had to find my own ways to get the actors for hogwarts legacy since ,wiki is not correct here , static object dont work, and imgui creating tab dont work either. so i went on to do seperate process, and this how i found whats the issue was atleast on the gui tab stuff. and this explains why gui dev is not working, register tab is not simply getting thought. i spammed that funktion, not a single log.

**Comment by UE4SS** [comment]
> orginally i wanted to make a cpp mod, but i had to find my own ways to get the actors for hogwarts legacy since ,wiki is not correct here , static object dont work, and imgui creating tab dont work either. so i went on to do seperate process, and this how i found whats the issue was atleast on the gui tab stuff. and this explains why gui dev is not working, register tab is not simply getting thought. i spammed that funktion, not a single log.

Maybe you made a mistake in your code and that's why the tab system isn't working.
Show your code for it.
I currently have a C++ mod running on 3.0 with working tabs.

**Comment by nexustheru** [comment]
i followed the wiki to letter, i put a log up right after this function. it never fire, inside registertab at bottom

**Comment by UE4SS** [comment]
> i had to find my own ways to get the actors for hogwarts legacy since ,wiki is not correct here , static object dont work

The wiki just shows an example of how to get an object, it's not incorrect, it's just that `StaticFindObject` is not applicable for everything.

**Comment by nexustheru** [comment]
i know that, why i used hook. but problem is the error is not getting thought. before version 3  that was rel few days ago, theres was no issue with live debugger or dumping headers or buttons.

**Comment by UE4SS** [comment]
I'm having problems understanding your broken English unfortunately.
Had you perhaps changed anything in UE4SS-settings.ini before you updated to 3.0 and forget to change it again after the update ?

**Comment by nexustheru** [comment]
never mind. i fix it myself, thank you for your help.

**Comment by Buckminsterfullerene02** [comment]
Just FYI, @UE4SS, the issue about the gui window being "all blank" (as this user described) happens for many games, and the fix for it is to change the renderer from opengl to dx11

**Comment by UE4SS** [comment]
> Just FYI, @UE4SS, the issue about the gui window being "all blank" (as this user described) happens for many games, and the fix for it is to change the renderer from opengl to dx11 in settings

That's kind of what I thought, which is why I was asking them if they'd changed anything in the settings file.
The idea was, they changed it and that's why it worked fine before, and then they updated and overrode the settings file and didn't make the change again.

**Comment by nexustheru** [comment]
> Just FYI, @UE4SS, the issue about the gui window being "all blank" (as this user described) happens for many games, and the fix for it is to change the renderer from opengl to dx11 in settings
nope, [Overrides]
; Path to the 'Mods' folder
; Default: <dll_directory>/Mods
ModsFolderPath =

[General]
EnableHotReloadSystem = 0

; Whether the cache system for AOBs will be used.
; Default: 1
UseCache = 1

; Whether caches will be invalidated if ue4ss.dll has changed
; Default: 1
InvalidateCacheIfDLLDiffers = 1

; The number of seconds the scanner will scan for before giving up
; Default: 30
SecondsToScanBeforeGivingUp = 30

; Whether to create UObject listeners in GUObjectArray to create a fast cache for use instead of iterating GUObjectArray.
; Setting this to false can help if you're experiencing a crash on startup.
; Default: true
bUseUObjectArrayCache = true

[EngineVersionOverride]
MajorVersion = 
MinorVersion = 

[ObjectDumper]
; Whether to force all assets to be loaded before dumping objects
; WARNING: Can require multiple gigabytes of extra memory
; WARNING: Is not stable & will crash the game if you load past the main menu after dumping
; Default: 0
LoadAllAssetsBeforeDumpingObjects = 0

[CXXHeaderGenerator]
; Whether to property offsets and sizes
; Default: 1
DumpOffsetsAndSizes = 1

; Whether memory layouts of classes and structs should be accurate
; This must be set to 1, if you want to use the generated headers in an actual C++ project
; When set to 0, padding member variables will not be generated
; NOTE: A VALUE OF 1 HAS NO PURPOSE YET! MEMORY LAYOUT IS NOT ACCURATE EITHER WAY!
; Default: 0
KeepMemoryLayout = 0

; Whether to force all assets to be loaded before generating headers
; WARNING: Can require multiple gigabytes of extra memory
; WARNING: Is not stable & will crash the game if you load past the main menu after dumping
; Default: 0
LoadAllAssetsBeforeGeneratingCXXHeaders = 0

[UHTHeaderGenerator]
; Whether to skip generating packages that belong to the engine
; Some games make alterations to the engine and for those games you might want to set this to 0
; Default: 0
IgnoreAllCoreEngineModules = 0

; Whether to skip generating the "Engine" and "CoreUObject" packages
; Default: 1
IgnoreEngineAndCoreUObject = 1

; Whether to force all UFUNCTION macros to have "BlueprintCallable"
; Note: This will cause some errors in the generated headers that you will need to manually fix
; Default: 1
MakeAllFunctionsBlueprintCallable = 1

; Whether to force all UPROPERTY macros to have "BlueprintReadWrite"
; Also forces all UPROPERTY macros to have "meta=(AllowPrivateAccess=true)"
; Default: 1
MakeAllPropertyBlueprintsReadWrite = 1

; Whether to force UENUM macros on enums to have 'BlueprintType' if the underlying type was implicit or uint8
; Note: This also forces the underlying type to be uint8 where the type would otherwise be implicit
; Default: 1
MakeEnumClassesBlueprintType = 1

; Whether to force "Config = Engine" on all UCLASS macros that use either one of:
; "DefaultConfig", "GlobalUserConfig" or "ProjectUserConfig"
; Default: 1
MakeAllConfigsEngineConfig = 1

[Debug]
; Whether to enable the external UE4SS debug console.
ConsoleEnabled = 1
GuiConsoleEnabled =0 
GuiConsoleVisible = 0

; Multiplier for Font Size within the Debug Gui
; Default: 1
GuiConsoleFontScaling = 1

; The API that will be used to render the GUI debug window.
; Valid values (case-insensitive): dx11, d3d11, opengl
; Default: opengl
GraphicsAPI = opengl

; How many objects to put in each group in the live view.
; A lower number means more groups but less lag when a group is open.
; A higher number means less groups but more lag when a group is open.
; Default: 32768
LiveViewObjectsPerGroup = 32768

[Threads]
; The number of threads that the sig scanner will use (not real cpu threads, can be over your physical & hyperthreading max)
; If the game is modular then multi-threading will always be off regardless of the settings in this file
; Min: 1
; Max: 4294967295
; Default: 8
SigScannerNumThreads = 8

; The minimum size that a module has to be in order for multi-threading to be enabled
; This should be large enough so that the cost of creating threads won't out-weigh the speed gained from scanning in multiple threads
; Min: 0
; Max: 4294967295
; Default: 16777216
SigScannerMultithreadingModuleSizeThreshold = 16777216

[Memory]
; The maximum memory usage (in percentage, see Task Manager %) allowed before asset loading (when LoadAllAssetsBefore* is 1) cannot happen.
; Once this percentage is reached, the asset loader will stop loading and whatever operation was in progress (object dump, or cxx generator) will continue.
; Default: 85
MaxMemoryUsageDuringAssetLoading = 80

[Hooks]
HookProcessInternal = 1
HookProcessLocalScriptFunction = 1
HookInitGameState = 1
HookCallFunctionByNameWithArguments = 1
HookBeginPlay  = 1
HookLocalPlayerExec = 1
FExecVTableOffsetInLocalPlayer = 0x28

[CrashDump]
EnableDumping = 1
FullMemoryDump = 0

[ExperimentalFeatures]
; Only enable these features if you know what you are doing.
GUIUFunctionCaller = 0
  only thing i changed was the debugger gui 1 or 0 then it got all weird. dosnt matter what i change im just gonna rebuild it tomrrow with pull and do proper test.

**Comment by nexustheru** [comment]
but im pore in english so i dont expect you to understand me. but im trying .

**Comment by nexustheru** [comment]
found the issue   ; The API that will be used to render the GUI debug window.
; Valid values (case-insensitive): dx11, d3d11, opengl
; Default: opengl
GraphicsAPI = dx11  <---- changed default to this, now its working

**Comment by Buckminsterfullerene02** [comment]
That is what I said, but well done for figuring it out yourself too
