### ISSUE TITLE
Keyword to split "Exclude class names" in live editor?

### ISSUE THREAD

**Issue by bryankhamly** [UE4SS-RE/RE-UE4SS#369]
Hey there, looked around the documentation and I couldn't find the answer. What is the keyword to split strings if I'm using exclude class names in the live editor?

**Comment by UE4SS** [comment]
The `Exclude class name` option isn't capable of taking in multiple strings.
The way it works is, if the supplied string is found anywhere in the class of the object, it won't be included in the search results.
This string is also unfortunately case-sensitive.

For example, `LocalPlayer` will exclude this result: `LocalPlayer /Engine/Transient.GameEngine_2147482623:LocalPlayer_2147482560`, and so will `Local` and `Player` because the class is `LocalPlayer`.

**Comment by bryankhamly** [comment]
Gotcha, thanks :)

**Comment by the1killer** [comment]
So is the documentation wrong then? says you can separate multiple by commas? 
https://docs.ue4ss.com/dev/feature-overview/live-view.html

**Comment by UE4SS** [comment]
> So is the documentation wrong then? says you can separate multiple by commas? https://docs.ue4ss.com/dev/feature-overview/live-view.html

The docs are correct.
The feature was added a bit after this issue was created: #472

**Comment by the1killer** [comment]
I could not get this to work with more than one specifier no matter the spacing, and tried commas or semicolons

<img width="418" height="327" alt="Image" src="https://github.com/user-attachments/assets/1f49671d-80c1-433d-a78c-43410afc5ab5" />

**Comment by UE4SS** [comment]
> I could not get this to work with more than one specifier no matter the spacing, and tried commas or semicolons
> <img alt="Image" width="418" height="327" src="https://private-user-images.githubusercontent.com/65697638/478256010-1f49671d-80c1-433d-a78c-43410afc5ab5.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTUyMjg3OTMsIm5iZiI6MTc1NTIyODQ5MywicGF0aCI6Ii82NTY5NzYzOC80NzgyNTYwMTAtMWY0OTY3MWQtODBjMS00MzNkLWE3OGMtNDM0MTBhZmM1YWI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODE1VDAzMjgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4ZDA3ODU0M2FiMzhlYzA0MjFlMjUzYzc3YjIwYWZhMTBhOGI3OGE0ZmViMDg1OTg2N2E0OWIzZmY5ZTdjNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YeicbeugyvaqAjE8WWUNWBSFsF7RD2M1FcUr6c0En3M">

Make a new issue, or this will likely get lost and forgotten very quickly.

**Comment by UE4SS** [comment]
It looks like you're using an old version of UE4SS though, so try the experimental release.
