### ISSUE TITLE
[BUG - 3.0.0] Game crash on startup

### ISSUE THREAD

**Issue by GMatrixGames** [UE4SS-RE/RE-UE4SS#371]
**Branch or Release**
3.0 Release

**Game and Engine Version**
[TRIBES 3: Rivals Demo](https://store.steampowered.com/app/2687970) (5.3)

**Describe the bug**
Bypassing EAC and launching goes as normal, but as soon as it reaches adding GUObjectArray listeners, it crashes due to over memory allocation. I haven't run into this with any other game during my testing time today.

**Mods directory**
N/A

**To Reproduce**
1. Launch game
2. Crash

**Expected behavior**
Game to not crash due to memory allocation error

**Screenshots and UE4SS Log**
Crash log in console:
![image](https://github.com/UE4SS-RE/RE-UE4SS/assets/25112532/d10f726e-b3af-4992-91c3-0527d00eaa31)
[UE4SS.log](https://github.com/UE4SS-RE/RE-UE4SS/files/14214267/UE4SS.log)

**Desktop (please complete the following information):**
 - OS: Win11

**Additional context**
N/A

**Comment by narknon** [comment]
Online PVP games are not supported.
