### ISSUE TITLE
[BUG - Release] UE4SS Causes Palworld to crash

### ISSUE THREAD

**Issue by jsauerland** [UE4SS-RE/RE-UE4SS#385]
**Branch or Release**
The Tag for the Release you are using, or the commit you used if you built from source yourself.
v3.0.0

**Game and Engine Version**
Game where the bug occurred, and the UE engine version of the game.
Palworld. Unknown UE Engine version

**Describe the bug**
When launching the game, game immediately crashes with the following errors. I re-installed the mods, but still didn't work... I provided the crashes.zip file. 

nhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x000001b336ced058

UE4SS
UE4SS
UE4SS
UE4SS
Palworld_WinGDK_Shipping
Palworld_WinGDK_Shipping
Palworld_WinGDK_Shipping
Palworld_WinGDK_Shipping
UE4SS
Palworld_WinGDK_Shipping
Palworld_WinGDK_Shipping
Palworld_WinGDK_Shipping
UE4SS
Palworld_WinGDK_Shipping
Palworld_WinGDK_Shipping
Palworld_WinGDK_Shipping
Palworld_WinGDK_Shipping
Palworld_WinGDK_Shipping
Palworld_WinGDK_Shipping
Palworld_WinGDK_Shipping
Palworld_WinGDK_Shipping
UE4SS
Palworld_WinGDK_Shipping
Palworld_WinGDK_Shipping
Palworld_WinGDK_Shipping
Palworld_WinGDK_Shipping
Palworld_WinGDK_Shipping
Palworld_WinGDK_Shipping
Palworld_WinGDK_Shipping
kernel32
ntdll

**Mods directory**
A zip of your Mods folder if you've installed any mods that don't come with UE4SS by default

vuxReduceFoodSpoilRate120 - https://www.nexusmods.com/palworld/mods/232
 - https://www.nexusmods.com/palworld/mods/11?tab=posts&BH=0

[Mods.zip](https://github.com/UE4SS-RE/RE-UE4SS/files/14268967/Mods.zip)

**To Reproduce**
1. Launch game
2. Attempt UHT Dump
3. See error in log

**Expected behavior**

The game should launch

**Screenshots and UE4SS Log**
If applicable, add screenshots to help explain your problem, and upload the log.
[Crashes.zip](https://github.com/UE4SS-RE/RE-UE4SS/files/14269351/Crashes.zip)

**Desktop (please complete the following information):**
 - OS: [e.g. Win10, Win11]

**Additional context**

**Comment by Afleeh** [comment]
I also have this crash. 

It is persistent once it happens and only uninstalling UE4SS resolves it. I can sometimes get some mods to work and at one time it was stable with 4 mods, but after one crash it crashes until everything is uninstalled. 

Tested on reinstalled fresh palworld as well.

the reading address is random/different each time

VCRUNTIME140
UE4SS
UE4SS
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
UE4SS
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
UE4SS
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
UE4SS
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
kernel32
ntdll

**Comment by noxbestia** [comment]
Adding my voice to the list of people experiencing this.

**Comment by Velathari** [comment]
Can confirm, I boot the game, close the intrusive popup, select multiplayer, close the second intrusive popup, select recent servers, select my server, password the box, hit the connect button, hit the redundant confirm button and at some point during the loading screen it crashes with the above crash log. Brute force reboot and retry eventually connects to server without crash.

**Comment by noxbestia** [comment]
I cleared my shader cache and I installed the zdev version of UE4SS.  The problem has not yet returned after several straight hours of gaming.

**Comment by UE4SS** [comment]
> > Can confirm, I boot the game, close the intrusive popup, select multiplayer, close the second intrusive popup, select recent servers, select my server, password the box, hit the connect button, hit the redundant confirm button and at some point during the loading screen it crashes with the above crash log. Brute force reboot and retry eventually connects to server without crash.
> 
> Those "instrusive popups" are the console and GUI windows, which is only enabled by default in the zDEV version of UE4SS - i.e. the version that is targeted at mod developers only. As you're clearly an end-user, I'm curious why you are using that version? Is the mod you're using telling you to use that?

They might've seen a reply by me to another issue where I asked someone to use the zDEV version because I couldn't get their dmp file working with the non-dev version.
I've also decided to always link to zDEV version to people whenever I request a user to test any particular build, just to make sure the dll & pdb match the ones I have so that I can actually do some debugging.

**Comment by Buckminsterfullerene02** [comment]
> I believe that poster meant the two popups from the game, not UE4SS.

Oh actually that would make sense because in the 3.0.0 release there is a bug where closing the GUI window crashes the game (fixed in next release hopefully being done today btw).

**Comment by noxbestia** [comment]
> > > Can confirm, I boot the game, close the intrusive popup, select multiplayer, close the second intrusive popup, select recent servers, select my server, password the box, hit the connect button, hit the redundant confirm button and at some point during the loading screen it crashes with the above crash log. Brute force reboot and retry eventually connects to server without crash.
> > 
> > 
> > Those "instrusive popups" are the console and GUI windows, which is only enabled by default in the zDEV version of UE4SS - i.e. the version that is targeted at mod developers only. As you're clearly an end-user, I'm curious why you are using that version? Is the mod you're using telling you to use that?
> 
> They might've seen a reply by me to another issue where I asked someone to use the zDEV version because I couldn't get their dmp file working with the non-dev version. I've also decided to always link to zDEV version to people whenever I request a user to test any particular build, just to make sure the dll & pdb match the ones I have so that I can actually do some debugging.

For clarification, I am the one who cleared their shader cache and installed the zDEV version, after digging into other bug reports for possible solutions.

BTW, clearing the shader cache fixes the "bending trees" problem that the game itself develops now and then.

**Comment by jsauerland** [comment]
The only "fix" I've found for this is a complete re-install of Palworld, and then, reinstalling UE4SS.

**Comment by Buckminsterfullerene02** [comment]
> > > > Can confirm, I boot the game, close the intrusive popup, select multiplayer, close the second intrusive popup, select recent servers, select my server, password the box, hit the connect button, hit the redundant confirm button and at some point during the loading screen it crashes with the above crash log. Brute force reboot and retry eventually connects to server without crash.
> > > 
> > > 
> > > Those "instrusive popups" are the console and GUI windows, which is only enabled by default in the zDEV version of UE4SS - i.e. the version that is targeted at mod developers only. As you're clearly an end-user, I'm curious why you are using that version? Is the mod you're using telling you to use that?
> > 
> > 
> > They might've seen a reply by me to another issue where I asked someone to use the zDEV version because I couldn't get their dmp file working with the non-dev version. I've also decided to always link to zDEV version to people whenever I request a user to test any particular build, just to make sure the dll & pdb match the ones I have so that I can actually do some debugging.
> 
> For clarification, I am the one who cleared their shader cache and installed the zDEV version, after digging into other bug reports for possible solutions.
> 
> BTW, clearing the shader cache fixes the "bending trees" problem that the game itself develops now and then.

> The only "fix" I've found for this is a complete re-install of Palworld, and then, reinstalling UE4SS.

So setting `bUseUObjectArrayCache = false` in `UE4SS-settings.ini` didn't work for either?

**Comment by Do0ks** [comment]
Following this threads advice it still errors with palworld_win64_shipping error on start up for me. Hopefully it's not a issue in further releases.

**Comment by Starcalled** [comment]
> So setting bUseUObjectArrayCache = false in UE4SS-settings.ini didn't work for either?

running UE4SS version 3.0.1, i had the same issue described in the thread, and this fixed the issue for me. no problems since.
