### ISSUE TITLE
[BUG - Release] Not loading with Palworld

### ISSUE THREAD

**Issue by MrZuribachi** [UE4SS-RE/RE-UE4SS#391]
**Branch or Release**
v3.0.0

**Game and Engine Version**
Palworld, not sure about engine version

**Describe the bug**
The game launches fine, but UESS4 is not loaded. I tried enabling the debug console, but it won't open, installing mods on the game that would take effect instantly (e.g. MapUnlocker) won't do anything. No crashes or errors on my end. I installed just like the instructions said, tried running Steam as admin, but to no avail.

**Mods directory**
Doesn't matter if I install any extra mods.

**Screenshots and UE4SS Log**
If applicable, add screenshots to help explain your problem, and upload the log.

**Desktop (please complete the following information):**
 - OS: Win10

**Comment by Buckminsterfullerene02** [comment]
Not enough info provided. Can you send a screenshot of the files in the folder you installed UE4SS into please?

**Comment by MrZuribachi** [comment]
Sure can do, this is the screenshot
![image](https://github.com/UE4SS-RE/RE-UE4SS/assets/6359603/96745361-8d41-49e5-9e89-9c00fafdb0ea)

**Comment by MrZuribachi** [comment]
The signatures folder is from the Palworld nexus, it was a desperate attempt at trying to get this thing working. But the outcome is no different.
Where would the log be located? Is it in the Win64? If so, it doesn't get generated

**Comment by MrZuribachi** [comment]
Just did so, but the same thing. (I have also tried deinstalling the game, removing all leftover files, reinstalling the game and installing UE4SS with a fresh download before).
Are there any prerequisites I'm not aware of, that I might be missing?

**Comment by Do0ks** [comment]
Same here. palworld_win64_shipping error on start up.

**Comment by narknon** [comment]
He's not getting an error so that's a different issue.

**Comment by Do0ks** [comment]
> He's not getting an error so that's a different issue.

Shoot, wrong thread. Good catch.

**Comment by sadmiroir** [comment]
Yeah.. XGP version same here, game always crash when loading save file or just create a new save. tried 3.0.1 still like this.
only can prive crash dmp file here, dont see any logs: https://drive.google.com/file/d/1JJc1eIha0ZUZegEmU-WFs5jyR-qJYf-x/view?usp=sharing

**Comment by Buckminsterfullerene02** [comment]
> Yeah.. XGP version same here, game always crash when loading save file or just create a new save. tried 3.0.1 still like this.
> only can prive crash dmp file here, dont see any logs: https://drive.google.com/file/d/1JJc1eIha0ZUZegEmU-WFs5jyR-qJYf-x/view?usp=sharing

This is also a different issue, please make a new one.

**Comment by MrZuribachi** [comment]
So, I finally got it working. I downloaded and installed the Visual C++ Redistributable 2015 which I didn't seem to have installed previously, and UE4SS is properly injecting and generating the log files. Had a crash upon loading my world, but that was fixed by setting bUseUObjectArrayCache to false in the .ini.
So thank you guys for trying to help, but this time the error was once again located between keyboard and the desk's chair

**Comment by narknon** [comment]
Odd, not sure why you'd need the redist to have it load the module, but good to know as a thing to try in the future.

**Comment by UE4SS** [comment]
> Yeah.. XGP version same here, game always crash when loading save file or just create a new save. tried 3.0.1 still like this. only can prive crash dmp file here, dont see any logs: https://drive.google.com/file/d/1JJc1eIha0ZUZegEmU-WFs5jyR-qJYf-x/view?usp=sharing

This crash is caused by having `bUseUObjectArrayCache` set to `true`, setting it to `false` should make this crash go away.

Note to maintainers: This does not solve the original problem, this is an entirely different problem, don't close this issue yet.

**Comment by buendva** [comment]
> So, I finally got it working. I downloaded and installed the Visual C++ Redistributable 2015 which I didn't seem to have installed previously, and UE4SS is properly injecting and generating the log files. Had a crash upon loading my world, but that was fixed by setting bUseUObjectArrayCache to false in the .ini. So thank you guys for trying to help, but this time the error was once again located between keyboard and the desk's chair

My situation is the same as yours. There is no response after importing UE4SS. However, after I installed Visual C++ Redistributable 2015 according to your method, my problem still did not solve. It seemed that nothing happened.
