### ISSUE TITLE
New Character Creation after installing UE4SS on my Palworld Server - UE4SS 3.0.1

### ISSUE THREAD

**Issue by Vampiresdawn8800** [UE4SS-RE/RE-UE4SS#405]
**Branch or Release**
3.0.1

**Game and Engine Version**

Palworld 0.1.4.1 with UE4SS 3.0.1

**Describe the bug**

Hi,

i tested to Install the Loader for the Mods on my Server. First i installed it and with it some Server Mods. Sadly after we started the Server we were all prompted to create a new Charakter. I thought it was one of the other Mods so i deinstalled all and tried step by step installation. First UE4SS before anything else. After just applying it to my server i tried to start the server just with UE4SS installed. I was prompted to create a new Charakter again. So it was UE4SS i guess. Someone has an Idea why this happens? If uninstalled again we all can use the Server normal again.

Any ideas? Any help is highly appreciated.

**Mods directory**

Only Default Download from GitHub

**To Reproduce**

1. We have an Server from https://c-area.host-unlimited.de with Premium Option (Windows 64 Server)
2. Stopping the Server and access with FileZilla FTP
3. Install UE4SS like described
4. Start Server
5. Launch Game and try to Connect to Server
6. New Character Creation promt, altrough if UE4SS is not installed we can use our normal Charakters

**Expected behavior**

Add the Ability to use the Mods from Nexus Mods expecially the Server Utility ones

**Screenshots and UE4SS Log**

N/A

**Desktop (please complete the following information):**
 
- OS: Win11

**Additional context**

N/A

**Comment by UE4SS** [comment]
This sounds very bizarre.
I can't think of a reason why UE4SS would cause this.
Maybe your server host detects that your running mods and automatically switches to a different "profile" for save files or something.
Are you 100% that this happens with just UE4SS installed ? Meaning without any UE4SS Lua/C++/BP mods installed and without any non-UE4SS mods installed.

**Comment by Vampiresdawn8800** [comment]
Thank you for your reply.

No the Server does not detect the Mods and create a new world/save file. The old world is still on the Server and if you create a new Character you can just walk up to our bases. So it´s more like he cant remember your Steam Login to be Connected with the Player GUID saved on the Server. 

Iam not exactly sure if you mean other things installed as the files in the 3.0.1 Download or just UE4SS without the Mods which come with it. At the moment i was talking about the full Package like you get it if downloaded from GitHub. Just installed that like described on the Server and rebootet the Server. If you try to connect to the Server you shall create a new Character. If i do there will even be a new Character GUID be created in the Worlds Player Save files. So it really seems as if the Server can´t remember your Steam Login to be connected with your old Character Save File.

And like i told before if you remove the whole UE4SS Stuff which comes with the Download from the Server your Charakter get´s instantly recognized and you get logged in like before. 

If anything i hope it will help other players. We will only have the Server for a few more Days until we stop playing for now since we are in the Endgame and wait for new Content but maybe we can figure out why that happens. Checked and the Server will still be available for 2 Days and 9 hours. 

If we don´t get it solved or if you think now, with the remaining time it´s a waste to try to figure it out, i can understand that. Then the Ticket can be closed. i would not be mad about it.

Thank you so far.

**Comment by UE4SS** [comment]
Unfortunately I have no idea what could be causing this.
I don't think it's worth investigating further unless other people report the same problem, especially considering I don't have the game so I can't even do any testing.

**Comment by Vampiresdawn8800** [comment]
Okay. Thank you so much for your Time. We will see what will happen if Palworld get´s an Update and we will Play again.

**Comment by ajm27** [comment]
I've also came across this bug. Perfectly fine windows server then as soon as I install UE4SS and sign back in, I have to make a new character.
I am using a hosting website but I don't think that would be the cause since I've reproduced the issue a couple of times reliably. Getting my server ported over to the new server (in working condition) then installing UE4SS and having issues.

**Comment by TheKogoro** [comment]
Same for me, i just installed UE4SS and the server want me to create a new character. If i uninstall UE4SS and launch the server i can login with my character.

**Comment by xmanney** [comment]
yeah same issue for me as well. after installing UE4SS on a dedicated server it prompts anyone that joins to create a new character.  As others stated, everything in the world is still there.  No fix i guess?

**Comment by TheKogoro** [comment]
> yeah same issue for me as well. after installing UE4SS on a dedicated server it prompts anyone that joins to create a new character. As others stated, everything in the world is still there. No fix i guess?

Try this One: https://github.com/UE4SS-RE/RE-UE4SS/releases/download/experimental/UE4SS_v3.0.1-39-g3320fc1.zip

For me that resolve my problem.

**Comment by xmanney** [comment]
> > yeah same issue for me as well. after installing UE4SS on a dedicated server it prompts anyone that joins to create a new character. As others stated, everything in the world is still there. No fix i guess?
> 
> Try this One: https://github.com/UE4SS-RE/RE-UE4SS/releases/download/experimental/UE4SS_v3.0.1-39-g3320fc1.zip
> 
> For me that resolve my problem.

ill give it a shot, thanks
