### ISSUE TITLE
Crashes on Palworld game launch after working for hours previous

### ISSUE THREAD

**Issue by Tensar-Tensar** [UE4SS-RE/RE-UE4SS#409]
**Branch or Release**
RE-UE4SS 2.5.2

**Game and Engine Version**
Palworld v0.1.4.1

**Describe the bug**
Was playing for a second time in two days after install and mod install. then crash to desktop, now it just launches and crashes to desktop with the following error listed in the error submission page:

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000010

XINPUT1_3
XINPUT1_3
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
XINPUT1_3
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
XINPUT1_3
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
XINPUT1_3
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
XINPUT1_3
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
XINPUT1_3
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
XINPUT1_3
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
XINPUT1_3
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
XINPUT1_3
Palworld_Win64_Shipping
XINPUT1_3
Palworld_Win64_Shipping
Palworld_Win64_Shipping
XINPUT1_3
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
kernel32
ntdll

**Mods directory**
[Mods.zip](https://github.com/UE4SS-RE/RE-UE4SS/files/14413862/Mods.zip)

**To Reproduce**
1. Launch game

**Desktop (please complete the following information):**
Win10

fairly new to modding in general, not sure what i screwed up, any help would be great. it worked for several hours yesterday but now wont stay launched when opened through vortex

**Comment by UE4SS** [comment]
Try the 3.0.1 release, and read the instructions for upgrading from 2.5 because there's an extremely important note about that.

**Comment by TheNicheGuy** [comment]
I have no coding or game creation experience, but I feel like I can confirm from my end that the 3.0.1v is causing this issue for me, possibly the mods relying on it as well. I started with the 3.0.1v yesterday before work to begin modding, and when I got home the game auto updated and wouldn't boot up anymore. The 1.5 update to palworld I'm pretty sure has broken the way UESS works so I'm assuming we wait for an update to correct this.
I'm pasting my crash log below in case if I'm wrong at all, but this is my hunch currently.

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000000

Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
kernel32
ntdll

**Comment by UE4SS** [comment]
> I have no coding or game creation experience, but I feel like I can confirm from my end that the 3.0.1v is causing this issue for me

One crash doesn't have to be the same as another.
Please make a new issue and follow the template, and remember to include the log file, and also the crash dump if available.

**Comment by TheNicheGuy** [comment]
Ah, I'll be sure to follow the guidelines, I'm new here and didn't know that, my apologies. I just want to fix my, and hopefully others', issues if it's happening and figured if others are having issues it more than likely could be relative to the update that just released; if I'm simply assuming ignorantly again: I apologize.
