### ISSUE TITLE
[PS] Scan failed v3.0.1

### ISSUE THREAD

**Issue by ZbitHound** [UE4SS-RE/RE-UE4SS#430]
Recently downloaded the files and installed them as directed. The .pak files all load and work fine. I'm having issues with the .lua and script files. I'm placing them in the Mods folder in Win64, but I get this:

**[2024-03-08 22:37:38] Console created
[2024-03-08 22:37:38] UE4SS - v3.0.1 Beta #0 - Git SHA #d935b5b
[2024-03-08 22:37:38] UE4SS Build Configuration: Game__Shipping__Win64 (MSVC)
[2024-03-08 22:37:38] Setting up mods...
[2024-03-08 22:37:38] Starting mods (from mods.txt load order)...
[2024-03-08 22:37:38] Starting mods (from enabled.txt, no defined load order)...
[2024-03-08 22:37:38] No specific game configuration found, using default configuration file
[2024-03-08 22:37:38] Config: Z:\home\user\snap\steam\common\.local\share\Steam\steamapps\common\Palworld\Pal\Binaries\Win64\UE4SS-settings.ini

[2024-03-08 22:37:38] root directory: Z:\home\user\snap\steam\common\.local\share\Steam\steamapps\common\Palworld\Pal\Binaries\Win64
[2024-03-08 22:37:38] working directory: Z:\home\user\snap\steam\common\.local\share\Steam\steamapps\common\Palworld\Pal\Binaries\Win64
[2024-03-08 22:37:38] game executable directory: Z:\home\user\snap\steam\common\.local\share\Steam\steamapps\common\Palworld\Pal\Binaries\Win64
[2024-03-08 22:37:38] game executable: Z:\home\user\snap\steam\common\.local\share\Steam\steamapps\common\Palworld\Pal\Binaries\Win64\Palworld-Win64-Shipping.exe (147044352 bytes)

[2024-03-08 22:37:38] mods directory: Z:\home\user\snap\steam\common\.local\share\Steam\steamapps\common\Palworld\Pal\Binaries\Win64\Mods
[2024-03-08 22:37:38] log directory: Z:\home\user\snap\steam\common\.local\share\Steam\steamapps\common\Palworld\Pal\Binaries\Win64
[2024-03-08 22:37:38] object dumper directory: Z:\home\user\snap\steam\common\.local\share\Steam\steamapps\common\Palworld\Pal\Binaries\Win64

[2024-03-08 22:37:38] PS Scan attempt 1
[2024-03-08 22:37:38] [PS] Reading image
[2024-03-08 22:37:38] [PS] Scan failed**

This failure continues until it gets to 99999 attempts and then just quits. Not sure what's happening. Do I have a setting off or something?

**Comment by LuciCMD** [comment]
It would be helpful to have some more information about your specific setup:

Which mods are you currently trying to use?
Are you using UE4SS signatures that you downloaded from NexusMods, or are you using signatures from another source?
Have you successfully used these mods before, or is this your first time attempting to use them?

Also, it doesn't hurt to try verifying your installation of Palworld through steam, if you have not done so already.

**Comment by ZbitHound** [comment]
> Which mods are you currently trying to use?
> Are you using UE4SS signatures that you downloaded from NexusMods, or are you using signatures from another source?
> Have you successfully used these mods before, or is this your first time attempting to use them?

1. I'm trying out the Toggle Lantern mod by xPYRO99 on the nexus. 
2. I'm using the files downloaded from here on Github. Particularly the latest version from the file UE4SS_v3.0.1.zip.
3. I have not used any script files successfully since install. Only .pak files work for me at this time. It's also my first time modding the game. I have no knowledge of modding this game yet.

Will verifying remove the mods or saves? If so that's fine, but I just want to know before I go ahead with it.

**Comment by LuciCMD** [comment]
I downloaded that mod and had no issues, so it doesn't seem like an with the mod itself
Make sure you don't have xinput1_3.dll in your Win64 folder. If you do, delete it
Make sure you have all of the mods that UE4SS came with, don't delete any of them, especially the keybind mod as I believe that is needed for Toggle Lantern.

Verifying through Steam will NOT remove mods or saves, it simply checks for any corrupted or missing files and re-downloads/fixes them if necessary.

**Comment by ZbitHound** [comment]
> I downloaded that mod and had no issues, so it doesn't seem like an issue with the mod itself Make sure you don't have xinput1_3.dll in your Win64 folder. If you do, delete it Make sure you have all of the mods that UE4SS came with, don't delete any of them
> 
> Verifying through Steam will NOT remove mods or saves, it simply checks for any corrupted or missing files and re-downloads/fixes them if necessary.

I'll try that. I didn't delete any files from the mod or manipulate anything outside of dragging and dropping. However, I never had the xinput1_3.dll file since the Xinput version isn't available in the file list. Could that be my issue?

**Comment by LuciCMD** [comment]
xinput was a file required for an older version of UE4SS, it is no longer required, but in the case of people upgrading from UE4SS 2.5.2, that file would need to be deleted. So I was just checking in case you had used a previous version of UE4SS. TLDR, it's not the issue in that case

**Comment by ZbitHound** [comment]
Ok. I've validated the files and I'm doing a fresh install of the mods. Maybe that will work. I'll try the scripts first and see if I can get them working. I'll update with the log info if needed. Thanks for the suggestions.

**Comment by ZbitHound** [comment]
Ok. I have added no mods and checked the log. It's the dame issue and I have all a fresh install. Validated files and everything. Whatever "PS" it's scanning, I'm not following what the issue is.

**Comment by UE4SS** [comment]
Please share your full log file.

The scan in question that's failing happens before Lua (script) mods and BP mods are loaded so those mods can't have anything to do with this problem.
Your log file doesn't mention anything about Lua scans so I'm fairly sure you don't have any custom signatures installed.

Since you didn't share your full log file, I'm basing what I'm about to say next on the chunk of the log you shared being repeated in a 100% identical way.
It means PS is failing in `read_image` in `patternsleuth/src/process/internal.rs` for an unknown reason.
If you share the full log file, we can confirm this and move forward.

**Comment by ZbitHound** [comment]
Here's the file. Like I was saying, it just repeats the scan attempt before failing. 
[Uploading UE4SS.log…]()

**Comment by UE4SS** [comment]
> Here's the file. Like I was saying, it just repeats the scan attempt before failing. Uploading UE4SS.log…

The upload failed.
You probably hit the `Comment ` button before it finished uploading.

**Comment by ZbitHound** [comment]
Yup. here's a second try.
[UE4SS.log](https://github.com/UE4SS-RE/RE-UE4SS/files/14544297/UE4SS.log)

**Comment by UE4SS** [comment]
Thank you.
I haven't seen the scanner fail this early, perhaps @trumank can enlighten us about this.

**Comment by aoqia194** [comment]
Perhaps it may have to do with UE4SS and Linux support as I saw that they are using Linux and Steam snap package.

**Comment by ZbitHound** [comment]
That is true. Since I'm using Proton, could that be the issue? If so, should I remap something?

**Comment by UE4SS** [comment]
> That is true. Since I'm using Proton, could that be the issue? If so, should I remap something?

I use Proton myself, although not for Palworld since I don't have it, and it works fine out of the box.

**Comment by ZbitHound** [comment]
Then I'm still stumped. I've been looking around and haven't found any solution yet. Seems I'm the first to encounter this?

**Comment by UE4SS** [comment]
> Then I'm still stumped. I've been looking around and haven't found any solution yet. Seems I'm the first to encounter this?

You're the first that I'm aware of.
Hopefully truman can look into this eventually.

**Comment by ZbitHound** [comment]
> > Then I'm still stumped. I've been looking around and haven't found any solution yet. Seems I'm the first to encounter this?
> 
> You're the first that I'm aware of. Hopefully truman can look into this eventually.

I appreciate you guys helping. Plebs like me would be nowhere without yall.

**Comment by ZbitHound** [comment]
Just noticed this in the README file....
![sad](https://github.com/UE4SS-RE/RE-UE4SS/assets/27394142/7b0c3617-d2a6-44a7-956e-d65107de36d3)

**Comment by UE4SS** [comment]
> Just noticed this in the README file.... ![sad](https://private-user-images.githubusercontent.com/27394142/311412256-7b0c3617-d2a6-44a7-956e-d65107de36d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5NTkzMDgsIm5iZiI6MTcwOTk1OTAwOCwicGF0aCI6Ii8yNzM5NDE0Mi8zMTE0MTIyNTYtN2IwYzM2MTctZDJhNi00NGE3LTk1NmUtZDY1MTA3ZGUzNmQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDA0MzY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1NDhkMzExNmVhZWM3NjE2Njg3MjNiNDZkZjlmMWU4MzllOWQwZjRiNjhhOTY3M2JkNDBiOTJkOGMwMTdiNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MYbKtcHO9HEYtlwpIHoCQXi1D_176NrsqxCVRv04CMc)

These are the requirements for building UE4SS from source, not for using the binary files in the releases section to mod a game.

**Comment by ZbitHound** [comment]
> > Just noticed this in the README file.... ![sad](https://private-user-images.githubusercontent.com/27394142/311412256-7b0c3617-d2a6-44a7-956e-d65107de36d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5NTkzMDgsIm5iZiI6MTcwOTk1OTAwOCwicGF0aCI6Ii8yNzM5NDE0Mi8zMTE0MTIyNTYtN2IwYzM2MTctZDJhNi00NGE3LTk1NmUtZDY1MTA3ZGUzNmQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDA0MzY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1NDhkMzExNmVhZWM3NjE2Njg3MjNiNDZkZjlmMWU4MzllOWQwZjRiNjhhOTY3M2JkNDBiOTJkOGMwMTdiNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MYbKtcHO9HEYtlwpIHoCQXi1D_176NrsqxCVRv04CMc)
> 
> These are the requirements for building UE4SS from source, not for using the binary files in the releases section to mod a game.

Ok. Thanks. I almost lost hope there...

**Comment by ZbitHound** [comment]
> It means PS is failing in `read_image` in `patternsleuth/src/process/internal.rs` for an unknown reason.

Is this in a `.dll` file or is this in a `.lua` file? Trying to see if there is anything I can do.

**Comment by UE4SS** [comment]
> > It means PS is failing in `read_image` in `patternsleuth/src/process/internal.rs` for an unknown reason.
> 
> Is this in a `.dll` file or is this in a `.lua` file? Trying to see if there is anything I can do.

It's a source file for a program called `patternsleuth` and that program is embedded in the UE4SS dll.
It's written in rust, that's where the `.rs` extension comes from.
This is the file: https://github.com/trumank/patternsleuth/blob/master/patternsleuth/src/process/internal.rs

**Comment by aoqia194** [comment]
I wonder if this could be the reason why...
https://github.com/trumank/patternsleuth/blob/67bd8d49101ace4c4844af1222ad091a4af78203/patternsleuth/src/process/internal.rs#L11

**Comment by ZbitHound** [comment]
> I wonder if this could be the reason why... https://github.com/trumank/patternsleuth/blob/67bd8d49101ace4c4844af1222ad091a4af78203/patternsleuth/src/process/internal.rs#L11
> 
> Edit: Forgot you were running it under wine/proton, if patternsleuth is detecting you're on Linux, then that is the reason. If it is detecting Windows, then it seems to be a possibly deeper issue.

The thing is, there is a branch there to detect Linux and Windows. So inside the shell, it should run like Windows. Unless I'm missing something, it should detect either one. However, it detects neither one from what I see. It's saying there is no image.

**Comment by trumank** [comment]
I neglected to do anything with with any errors that come from reading the image from memory but you would have to log it out here to see what it is: https://github.com/UE4SS-RE/RE-UE4SS/blob/332eea5711d036edd428b733f27214e8128e3d96/deps/first/patternsleuth_bind/src/lib.rs#L176-L179 UE4SS

**Comment by ZbitHound** [comment]
Is this something I can do? Will I find a log to explain what's happening? Or is coding needed? I'm still learning and afraid of messing up stuff.

**Comment by ZbitHound** [comment]
I'm still checking in from time to time. Still haven't managed to find a solution yet.

**Comment by ZbitHound** [comment]
Changed directory to deb instead of snap and it worked. This is no longer an issue for me.
