### ISSUE TITLE
make experimental release bug

### ISSUE THREAD

**Issue by acyc070** [UE4SS-RE/RE-UE4SS#437]
[make-release]
fetch-pack: invalid index-pack output
[make-release]
early EOF
[make-release]
fetch-pack: invalid index-pack output

**Comment by Buckminsterfullerene02** [comment]
Where are you trying to run this?

**Comment by UE4SS** [comment]
If you're referring to github actions sometimes failing to clone the repo, we're aware of this problem but we don't have a solution.

**Comment by nexustheru** [comment]
https://stackoverflow.com/questions/21277806/fatal-early-eof-fatal-index-pack-failed?
