### ISSUE TITLE
[BUG - 2dad368] Standard C++ Header Generation does not work in certain UE4 versions.

### ISSUE THREAD

**Issue by matty45** [UE4SS-RE/RE-UE4SS#44]
**Branch or Release**
[2dad368](https://github.com/UE4SS-RE/RE-UE4SS/commit/2dad368e25d21eac56a615bb75d654224905b546)

**Game and Engine Version**
4.21.1

**Describe the bug**
The game fails to dump the headers due to it trying to fetch a variable that is not available in 4.21.1.

**To Reproduce**
1. Launch game
2. Attempt C++ Header Dump
3. See error in log

**Expected behavior**
A working dump.

**Screenshots and UE4SS Log**
[UE4SS.log](https://github.com/UE4SS-RE/RE-UE4SS/files/10484526/UE4SS.log)

**Desktop (please complete the following information):**
 - OS: Win 10 AME

**Comment by UE4SS** [comment]
Could you sure your UE4SS_Signatures folder ?

**Comment by UE4SS** [comment]
According to your log file, this is `Halo The Master Chief Collection`, and after fixing the signature problems, the CXX generator seems to be working.

Try these signatures and also manually set the game version to 4.21 in UE4SS-settings.ini:
[UE4SS_Signatures.zip](https://github.com/UE4SS-RE/RE-UE4SS/files/10488581/UE4SS_Signatures.zip)

**Comment by matty45** [comment]
[sigs.zip](https://github.com/UE4SS-RE/RE-UE4SS/files/10494351/sigs.zip)

Still get the same error, ive uploaded current signatures and settings file.

**Comment by matty45** [comment]
Everything was compiled straight from the latest commit, used the files from the staging folder.

**Comment by UE4SS** [comment]
I've been able to repro the problem using your settings file.

**Comment by matty45** [comment]
Hm, turns out things work out just fine using a fresh install of the latest release (2.2.1 hotfix) and the signatures that you have given me.

**Comment by UE4SS** [comment]
It's only a problem when `KeepMemoryLayout` is set to `1` in the settings file.
I will get this fixed.

**Comment by matty45** [comment]
was just about to say it was that setting, lol, wanted to check if it did something either way, which it does

**Comment by UE4SS** [comment]
This has now been fixed in the UEPseudo repo.
It'll show up in this repo eventually, this issue will be closed once the submodule has been updated.

**Comment by narknon** [comment]
Fixed on 2.XDev
