### ISSUE TITLE
[BUG - Release] Can't inject DLL.

### ISSUE THREAD

**Issue by Peyton2017** [UE4SS-RE/RE-UE4SS#445]
**Branch or Release**
Current, regular. Not experimental.

**Game and Engine Version**
Beasts of Bermuda, UE 4.26

**Describe the bug**
When I inject the DLL manually I get an error "Failed to write crashdump file, reason: 80070057"

**To Reproduce**
1. Launch game
2. Inject UE4SS.dll
3. Get error popup.

**Expected behavior**
No errors, so I can dump information.

**Screenshots, UE4SS Log, and .dmp file**
[crash_2024_03_26_16_23_34.dmp](https://github.com/UE4SS-RE/RE-UE4SS/files/14761660/crash_2024_03_26_16_23_34.dmp)
![image](https://github.com/UE4SS-RE/RE-UE4SS/assets/28621717/70411348-b424-400b-a0ff-1989d87aed9e)

**Desktop (please complete the following information):**
 - OS: [e.g. Win10, Win11]
Win 11.

**Comment by Peyton2017** [comment]
Whenever I try to launch the game, with dwmapi.dll included in the directory, I get this:

![image](https://github.com/UE4SS-RE/RE-UE4SS/assets/28621717/172cf328-c063-4e15-8109-a147a2ba4f3f)
[crash_2024_03_26_16_32_50.zip](https://github.com/UE4SS-RE/RE-UE4SS/files/14761695/crash_2024_03_26_16_32_50.zip)

**Comment by UE4SS** [comment]
I'm unable to debug this.
For some reason I'm getting missing frames with the second crash dump (the first dump is 0 bytes big and invalid).
This doesn't usually happen with our .dmp files, typically you can still see UE4SS in the call stack.
![2024-03-26_17-38_vs_missing_frames](https://github.com/UE4SS-RE/RE-UE4SS/assets/91646798/6972b470-1b0c-4de1-9ac0-08e08d43d3fa)

**Comment by Peyton2017** [comment]
What am I to try differently?

**Comment by UE4SS** [comment]
The whole Win64 directory (exe + all dlls) could be useful in debugging this.

**Comment by Peyton2017** [comment]
Alright, I will post it soon.

**Comment by UE4SS** [comment]
This is an online only game, we don't support those.
