### ISSUE TITLE
[BUG - Release] Palword XBox Version not loading any mods

### ISSUE THREAD

**Issue by ifalatik** [UE4SS-RE/RE-UE4SS#450]
**Branch or Release**
3.0.1

**Game and Engine Version**
Palworld, UE5.1

**Describe the bug**
I was initially trying to install this mod: https://www.nexusmods.com/palworld/mods/437
During my first try I put the extracted files into `Palworld\Content\Pal\Binaries\WinGDK`, removed all Mods from the `Mods` directory and put only `BPModLoaderMod : 1` into the `mods.txt`.
I moved the `PalIVs.pak` into `Palworld\Content\Pal\Content\Paks\LogicMods`. I also changed `bUseUObjectArrayCache` to `false`.
After starting the game, nothing had changed.
So I removed everything again, and put just the contents of the release into the `WinGDK` folder, changed nothing but `bUseUObjectArrayCache` this time. Again, after starting the game, nothing seems to have changed. From the logs I can tell `F10` is supposed to open a console, though nothing happens. This leads me to believe UE4SS is again not working properly.

**Mods directory**
Just the default mods from the zip

**To Reproduce**
Described above

**Expected behavior**
I'd expect the mods to work.

**Screenshots, UE4SS Log, and .dmp file**
[UE4SS.log](https://github.com/UE4SS-RE/RE-UE4SS/files/14857157/UE4SS.log)
I don't have any dump files. If further files are required, please tell me how to obtain them.

**Desktop (please complete the following information):**
 - OS: Win11 Pro

**Comment by UE4SS** [comment]
I think you've put the pak file in the wrong directory.
It should be in `<dir-containing-Palworld.exe>/Pal/Content/Paks/LogicMods`.

**Comment by ifalatik** [comment]
Well for XBOX there is no `Palworld.exe`, I just have the `Palworld-WinGDK-Shipping.exe` in `Palword\Content\Pal\Binaries\WinGDK`. From the documentation of the mod it seems this was the correct directory:
```
Navigate to your PalWorld game directory
﻿Steam: Right click on game in Steam -> Manage -> Browse Local Files
﻿Xbox App: Select Palworld, click the three dot button ( ... ) and click Manage from the dropdown.  Then select the FILES tab ﻿and click BROWSE...
Navigate to the LogicMods folder in your PalWorld game directory:
...\Pal\Content\Paks\LogicMods\
Download and extract the latest version of the mod from the files tab
Move the .pak file from the extracted mod folder to the LogicMods folder from above (...\Pal\Content\Paks\LogicMods\).  Be sure to only copy the .pak and not the entire folder.
```

From the troubleshooting page (https://www.nexusmods.com/palworld/articles/67)
```
Also make sure that the LogicMod .pak file is in the correct location:
...\Palworld\Pal\Content\Paks\LogicMods\

If you navigate to this LogicMods folder and go up 1 directory, you should see Pal-WinGDK.pak.  If you don't, your mod is installed in the incorrect place.
```
The `Palworld\Content\Pal\Content\Paks` directory contains `Pal-WindGDK.pak`.

**Comment by UE4SS** [comment]
I guess I'm not aware of the structural differences between Win64 and WinGDK games.

I'm currently out of ideas for what could be causing this problem.
The log file says everything loaded correctly.
Is the log file from before or after you removed the pak file ? UE4SS isn't finding any BP mods according to the log file.

**Comment by UE4SS** [comment]
After checking the log again, it appears that the LogicMods directory wasn't found and was therefore created automatically.
This suggests that you hadn't yet installed the pak file at this time.
Can you upload a log file from after you installed the pak file ?

**Comment by Okaetsu** [comment]
> Well for XBOX there is no `Palworld.exe`, I just have the `Palworld-WinGDK-Shipping.exe` in `Palword\Content\Pal\Binaries\WinGDK`. From the documentation of the mod it seems this was the correct directory:

Based on the path in your log file, the path to LogicMods would be the following:
`C:\Program Files\WindowsApps\PocketpairInc.Palworld_0.0.49074.0_x64__ad4psfrxyesvt\Pal\Content\Paks\LogicMods`

You most likely installed the pak file into the wrong directory since I know a couple people who are using UE4SS on Xbox version just fine. Also do keep in mind you may run into issues like crashing with certain mods after the most recent game update (As of me posting this).

**Comment by ifalatik** [comment]
I just got back to my PC and was looking to try out your suggestions from yesterday, but your comment beat me to it. You were right, after putting the .pak into the described directory it now works. I guess what was the issue yesterday (as this is the same directory I used before), was that I also removed the `BPModLoaderMod` directory from the Mods folder.

**Comment by ifalatik** [comment]
Also the XBOX Version seems to have not yet received the update, so for now I'm left with a working mod and not crashing game :D

**Comment by Caesezr** [comment]
Hi, not sure if you gonna see this. Could you tell me the exact pathway to where you moved the .pak files? I'm struggling. Thanks
