### ISSUE TITLE
[BUG - Release] palworld v0.2.0.6 seems not to work

### ISSUE THREAD

**Issue by 4everdestiny** [UE4SS-RE/RE-UE4SS#451]
palworld v0.2.0.6 seems not to work

**Comment by Okaetsu** [comment]
Have you tried uninstalling the mods you are using? I am using UE4SS on the newest patch and it's working fine for me, but I had to remove specific mods so I would count this more as a mod related issue rather than anything UE4SS related.

**Comment by 4everdestiny** [comment]
it's ok when I launch the game, but when I open a save, it will crash:
![1712232292333](https://github.com/UE4SS-RE/RE-UE4SS/assets/14860345/007bb5a8-55a7-4e51-9a98-e5a9d538ad83)
and my logicMods directory is empty,
![image](https://github.com/UE4SS-RE/RE-UE4SS/assets/14860345/d7e849b3-b30b-41d0-b42a-d946ed5aa895)
the Win64/Mods has only the mod you give
![image](https://github.com/UE4SS-RE/RE-UE4SS/assets/14860345/be307da4-a162-4fad-a02e-1fb1da000162)
what's the problem?
the attach files are the crash dump.
[UECC-Windows-2E9815AE4C7E8FE03CB0BDA44A5B1747_0000.zip](https://github.com/UE4SS-RE/RE-UE4SS/files/14866130/UECC-Windows-2E9815AE4C7E8FE03CB0BDA44A5B1747_0000.zip)

**Comment by 4everdestiny** [comment]
the save is the new game i created after v0.2.0.6 patch

**Comment by Okaetsu** [comment]
Could you show your Paks folder? Also have you set `bUseUObjectArrayCache` to false in UE4SS-settings.ini?

**Comment by 4everdestiny** [comment]
set bUseUObjectArrayCache to false worked, thank you very much!!!
