### ISSUE TITLE
Optimization flags wrong & no symbols with xmake

### ISSUE THREAD

**Issue by UE4SS** [UE4SS-RE/RE-UE4SS#462]
The xmake build system isn't properly setting optimization flags.

The optimization flags (/O2, /O0d) aren't being set for any of the configs.
The PDB files aren't being generated properly either, which I noticed when I tried to debug a problem and VS was unable to find any source information in the PDB.

It seems to me that the PDB problem can be solved by adding `["symbols"] = {"debug"}` to all the configs instead of just the shipping config.
The optimization flags problem is not one that I know how to fix.

I haven't made a PR for the PDB problem.
I suspect it will involve working on the same file as the optimization fix and I don't feel like dealing with the conflict so if whoever works on the optimization fix doesn't include the PDB fix as well then I'll make a PR after the optimization fix has been merged.

**Comment by bitonality** [comment]
Thanks for bringing the missing flags to my attention. 
```
//Flags used by the CXX compiler during RELEASE builds.
CMAKE_CXX_FLAGS_RELEASE:STRING=/O2 /Ob2 /DNDEBUG

//Flags used by the CXX compiler during RELWITHDEBINFO builds.
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=/Zi /O2 /Ob1 /DNDEBUG

//Flags used by the CXX compiler during DEBUG builds.
CMAKE_CXX_FLAGS_DEBUG:STRING=/Zi /Ob0 /Od /RTC1
```

I think xmake's optimization setting is sufficient without us having to manually add the flags for each compiler.

```lua
set_optimize("none")
-- /Od (gcc/clang) /O0 (msvc)
set_optimize("faster")
-- /O2 (gcc/clang/msvc)
```

**Comment by UE4SS** [comment]
I don't like how xmakes `fastest` option (/Ox, MSVC, -O3 clang) is the fastest option for clang but not for MSVC.
For MSVC `faster` (/O2 MSVC, -O2 clang) is the fastest option, but it's not for clang.
This is because MSVCs `/Ox` is actually a subset of `/O2`, meaning it has less optimizations included in it.
I wonder why xmake does it like this.

References
https://xmake.io/#/manual/project_target?id=targetset_optimize
https://learn.microsoft.com/en-us/cpp/build/reference/ox-full-optimization?view=msvc-170

**Comment by bitonality** [comment]
Looks like the docs are outdated for xmake. I just checked the source and these are the actual mappings for clang/gcc/cl.

```lua
--Clang
            none       = "-O0"
        ,   fast       = "-O1"
        ,   faster     = "-O2"
        ,   fastest    = "-O3"
        ,   smallest   = "-Oz" -- smaller than -Os
        ,   aggressive = "-Ofast"
        
--Gcc
            none       = "-O0"
        ,   fast       = "-O1"
        ,   faster     = "-O2"
        ,   fastest    = "-O3"
        ,   smallest   = "-Os"
        ,   aggressive = "-Ofast"
--Msvc
        none        = "-Od"
    ,   faster      = "-Ox"
    ,   fastest     = "-O2 -fp:fast"
    ,   smallest    = "-O1 -GL" -- /GL and (/OPT:REF is on by default in linker), we need to enable /ltcg
    ,   aggressive  = "-O2 -fp:fast"
```

**Comment by UE4SS** [comment]
In that case we should definitely be using `fastest`, not `faster`.

**Comment by bitonality** [comment]
Should be as easy as adding

```lua
CONFIG_TYPES = {
    ["Dev"] = {
        ["defines"] = {
            "UE_BUILD_DEVELOPMENT",
            "STATS"
        },
        ["optimize"] = {"none"}
    },
    ["Debug"] = {
        ["defines"] = {
            "UE_BUILD_DEBUG"
        },
        ["optimize"] = {"none"}
    },
    ["Shipping"] = {
        ["symbols"] = {"debug"},
        ["defines"] = {
            "UE_BUILD_SHIPPING"
        },
        ["optimize"] = {"fastest"}
    },
    ["Test"] = {
        ["defines"] = {
            "UE_BUILD_TEST",
            "STATS"
        },
        ["optimize"] = {"none"}
    }
}
```

Which makes it possible to add the symbols and fix the optimization flags in the same PR. Do we want symbols for every type of build?

**Comment by UE4SS** [comment]
> Should be as easy as adding

I tried this and it seemed to work for building via CLI, but when generating a VS project all targets had the same optimization flags.
Could you try it ? Maybe I messed it up.

> Do we want symbols for every type of build?

I don't see why not, any of them might need debugging at some point and it would be annoying to have to change it every time a debugging session needs to happen.
