### ISSUE TITLE
[BUG - Dev] xmake debug build regression

### ISSUE THREAD

**Issue by kohanis** [UE4SS-RE/RE-UE4SS#473]
**Branch or Release**
Current main (https://github.com/UE4SS-RE/RE-UE4SS/commit/cb5823ddc4066459d3393e2fb85fca2a2c219b34)

**Game and Engine Version**
At least grounded 1.4.0.4495 Rel (ue 4.27.2) and palworld 0.2.2.0 (ue 5.1.1)

**Describe the bug**
With debug and dev builds from xmake at some point of game loading there's debug assertion fail
In palworld at initial menu loading
In grounded at save loading

**Mods directory**
Can be empty, doesn't matter

**To Reproduce**
1. Compile ue4ss with Game__Dev__Win64 or Game__Debug__Win64 profile
2. Launch game with it injected
3. Try to load game world

<details>
<summary>Screenshots, UE4SS Log, and .dmp file</summary>

![image](https://github.com/UE4SS-RE/RE-UE4SS/assets/10516862/bc4fd213-6822-42f1-8365-f5ee0adfbe87)

</details>

**Desktop (please complete the following information):**
 - OS: Win11

**Comment by UE4SS** [comment]
I believe I've reproduced this problem, working on a fix now.

**Comment by UE4SS** [comment]
I've got a potential fix for this.
Could you try this experimental build: https://github.com/UE4SS-RE/RE-UE4SS/releases/download/experimental/zDEV-UE4SS_v3.0.1-54-g3976965.zip
Let me know if it solves your problem.

**Comment by kohanis** [comment]
Positive, built Game__Debug__Win64 from a branch, don’t see any crashes
