### ISSUE TITLE
[BUG - Release] TArray<AActor*>& outparam access violation

### ISSUE THREAD

**Issue by kohanis** [UE4SS-RE/RE-UE4SS#474]
**Branch or Release**
https://github.com/UE4SS-RE/RE-UE4SS/tree/v3.0.1 / https://github.com/UE4SS-RE/RE-UE4SS/commit/cb5823ddc4066459d3393e2fb85fca2a2c219b34

**Game and Engine Version**
At least grounded 1.4.0.4495 Rel (ue 4.27.2) and palworld 0.2.2.0 (ue 5.1.1), most likely any

**Describe the bug**
Using any function with TArray<AActor*>& out param results in crash with 0xc0000005
Edit: probably any TArray<UObject*>&

**Mods directory**
Example mod: [Mods.zip](https://github.com/UE4SS-RE/RE-UE4SS/files/15023166/Mods.zip)

**To Reproduce**
1. Launch game
2. Press ctrl + num1 inside game world

**Expected behavior**
Outparam set

**Screenshots, UE4SS Log, and .dmp file**
[UE4SS.log](https://github.com/UE4SS-RE/RE-UE4SS/files/15023252/UE4SS.log)
[crash_2024_04_18_10_03_47.zip](https://github.com/UE4SS-RE/RE-UE4SS/files/15023200/crash_2024_04_18_10_03_47.zip)
from grounded with 3.0.1 release

**Desktop (please complete the following information):**
 - OS: Win11

**Comment by UE4SS** [comment]
I think I figured out the problem.
Please try this version: https://github.com/UE4SS-RE/RE-UE4SS/releases/download/experimental/zDEV-UE4SS_v3.0.1-54-g7f6d0c7.zip

**Comment by kohanis** [comment]
Yes, my original case with SphereOverlapActors and GetAllActorsOfClass now works. Thanks
