### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by acyc070** [UE4SS-RE/RE-UE4SS#480]
i'm making funny language .locres for ue 5.1.1 game. but the game is packed into ucas, utoc files and it's size is around 36 GB, i don't want to unpack them. i heard about bp mod loader, but it didn't work

**Comment by Buckminsterfullerene02** [comment]
You can't replace .locres with bp mod loader. You need to use other tools that [you can find here](https://github.com/Buckminsterfullerene02/UE-Modding-Tools).

**Comment by acyc070** [comment]
i didn't find any working ue 5 mod loader in your link

**Comment by acyc070** [comment]
hello?

**Comment by UE4SS** [comment]
Be patient.
People are busy.

**Comment by Buckminsterfullerene02** [comment]
![image](https://github.com/UE4SS-RE/RE-UE4SS/assets/84156063/5c6ab5c5-ad05-4de8-9781-95f73214409f)
![image](https://github.com/UE4SS-RE/RE-UE4SS/assets/84156063/e91b0b3d-c21d-4547-b219-da29caedb67d)

Please wait for someone to help you in the discord, please don't keep spamming here or in uassetgui issues. You don't need a mod loader for your mod.
