### ISSUE TITLE
[BUG - Release] Live View returns wrong address of a function in UE4 4.19

### ISSUE THREAD

**Issue by dragitz** [UE4SS-RE/RE-UE4SS#482]
**Branch or Release**
Release v3.0.1 compiled zDEV-UE4SS_v3.0.1.zip 

**Game and Engine Version**
4.19.2.0

**Describe the bug**
As seen in the screenshot, the address displayed at the bottom does not point to the method, this is because in 4.19 the correct offset is +B0 (newer UE4 versions have it at D8, UE5 may have it at E0 depending on the version)

Instead, an address is given that points to data, resulting in gibberish instructions

**Mods directory**
None installed

**To Reproduce**
1. Launch 4.19 UE4 game
2. Lookup GetVelocity (or any other function) in Live View tab
3. Address shown is obtained from the wrong offset

**Expected behavior**
The correct address of the method (Actor:GetVelocity() in this case) in memory

**Screenshots, UE4SS Log, and .dmp file**
If applicable, add screenshots to help explain your problem, and upload the log and .dmp files located in the Win64 directory.
![immagine](https://github.com/UE4SS-RE/RE-UE4SS/assets/8062792/f1105def-1a6a-4b03-9f5e-c849d2769edd)

[UE4SS.log](https://github.com/UE4SS-RE/RE-UE4SS/files/15066824/UE4SS.log)

**Desktop:**
 - OS: Win10

**Additional context**
Currently reversing actor functions for a old-ish game

**Comment by UE4SS** [comment]
This behavior is correct.
The address displayed in the live view tab doesn't correspond to `UFunction::Func`, but rather to the UFunction object itself which when you add 0xB0 will get you the address of `UFunction::Func`.
