### ISSUE TITLE
[Question] Can this tool be used to add/modify localization in the game?

### ISSUE THREAD

**Issue by Release** [UE4SS-RE/RE-UE4SS#492]
Sorry for asking this question, but I looked through possible links and still couldn't find the answer.
Actually, the question is in the title of the topic.
Can it be used to somehow influence the localizations available in the game?
For example, load a modified Game.locres, packed or not. Or some other way.
And is it possible to add a localization language using this tool?

**Comment by Buckminsterfullerene02** [comment]
You can load modified Game.locres by using simple pak patching methods, you don't need ue4ss for this. If localisation is stored in datatables, in the future when #260 is released it will be possible to edit datatables in lua or c++ mod without breaking things if other mods try to do the same thing. But you can still just edit datatable in an asset editor like uassetgui and then pak that as a replacement mod, don't need ue4ss for that. And again if strings are hardcoded in kismet bytecode you need to use uassetgui to edit that as a replacement mod. 

So the anwer to your question is, for the most part no, this tool isn't used for localisation modding.
