### ISSUE TITLE
[BUG - CI] CI fails during checkout (again, different error)

### ISSUE THREAD

**Issue by UE4SS** [UE4SS-RE/RE-UE4SS#510]
This is a different error than the one we used to run into constantly before.
This new error has shown up twice in a row so far.
See: https://github.com/UE4SS-RE/RE-UE4SS/actions/runs/9127615715/job/25098260556

**Comment by Buckminsterfullerene02** [comment]
The commit sha of UEPseudo main is: 648ef9d93215869772a36757c35bcceab8757fe9, which does not match up with the sha it's trying to checkout. So clearly the submodule has been updated incorrectly.

**Comment by Buckminsterfullerene02** [comment]
Hmm, after 5.4 support merged on UEPseudo, and trying to run update submodule release action, it fails to find latest commit... something is definately very broken... 🤔 

![image](https://github.com/UE4SS-RE/RE-UE4SS/assets/84156063/3df4f15e-bdfa-430a-9cff-cfb10e03a4c2)

**Comment by Buckminsterfullerene02** [comment]
Fixed by pushing valid hash
