### ISSUE TITLE
[Improvement] Allow vsproj generation of a subset of allowed xmake modes

### ISSUE THREAD

**Issue by bitonality** [UE4SS-RE/RE-UE4SS#526]
Mod authors often only want to 
`xmake project -k vsxmake2022 -m Game__Shipping__Win64, Game__Debug__Win64`
I'll see if that's supportable.

**Comment by Buckminsterfullerene02** [comment]
Can this be closed as this feature exists in main?

**Comment by UE4SS** [comment]
> Can this be closed as this feature exists in main?

Yeah I don't see why not.
