### ISSUE TITLE
[BUG - Release] Serum (ue 5.4Fatal Error on startup

### ISSUE THREAD

**Issue by Egaliterrier** [UE4SS-RE/RE-UE4SS#528]
**Branch or Release**
The Tag for the Release you are using, or the commit you used if you built from source yourself.

**Game and Engine Version**
Game where the bug occurred, and the UE engine version of the game.

**Describe the bug**

**Mods directory**
A zip of your Mods folder if you've installed any mods that don't come with UE4SS by default

**To Reproduce**
1. Launch game
2. Attempt UHT Dump
3. See error in log

**Expected behavior**

**Screenshots, UE4SS Log, and .dmp file**
If applicable, add screenshots to help explain your problem, and upload the log and .dmp files located in the Win64 directory.

**Desktop (please complete the following information):**
 - OS: [e.g. Win10, Win11]

**Additional context**

**Comment by UE4SS** [comment]
You have to actually describe what the problem is, and provide the necessary information if applicable to your problem.

**Comment by Egaliterrier** [comment]
Yeah, no idea why this was posted, don't recall clicking submit before finishing the report
