### ISSUE TITLE
Mods folder

### ISSUE THREAD

**Issue by narknon** [UE4SS-RE/RE-UE4SS#538]
In latest experimental packaging, Mods folder is copied in as a subfolder of itself.  I believe this is ever since the pathing changes.

**Comment by narknon** [comment]
@UE4SS you approved this PR and it was merged right after changes I requested were made and before I had a chance to re-review.

**Comment by UE4SS** [comment]
> @UE4SS you approved this PR and it was merged right after changes I requested were made and before I had a chance to re-review.

It's not my PR, nor is the change in question mine, nor would I be the best person to look at this, hence why I removed myself.
@Buckminsterfullerene02 Implemented these changes, they are the ones best fit to look into this problem, I will wait for them.

As far as my approval is concerned, one person cannot be expected to find every single possible fault.
People are fallible, that's human nature.
If someone merges a PR after I approve and without waiting for someone else to also approve, why is that my fault ? Why is it my responsibility to fix potential problems ?
Sure I'll do my best to fix the problem if the author of the PR refuses or is unable to fix it but I see no reason why you should drag me into this before letting the original author give it a shot first.
