### ISSUE TITLE
[BUG - Release] Game crashes on start

### ISSUE THREAD

**Issue by Symbai** [UE4SS-RE/RE-UE4SS#548]
**Branch or Release**
v3.0.1

**Game and Engine Version**
Soulmask (Steam) UE 4.27.2.0

**Describe the bug**
Copied files to Win64 folder. When I start the game it immediately crashes (the process closes itself. No error displayed)

**Mods directory**

**To Reproduce**
1. Launch game

**Expected behavior**
No crash

**Screenshots, UE4SS Log, and .dmp file**

**Desktop (please complete the following information):**
 - OS: Win11

**Additional context**

**Comment by Buckminsterfullerene02** [comment]
We are going to more info. Please upload the UE4SS.log and the crash.dmp

**Comment by Egaliterrier** [comment]
Had the same issue, game doesn't crash per se, it just doesn't even start. Older versions of ue4ss using xinput work.

**Comment by Symbai** [comment]
There is no log and no dmp file

**Comment by Egaliterrier** [comment]
using zDEV-UE4SS_Xinput_v2.5.2-247-g92ccace.zip I get this:
![Screenshot 2024-06-01 231607](https://github.com/UE4SS-RE/RE-UE4SS/assets/6256553/6d315bb7-4f13-407a-a66d-043b6844c4ec)

**Comment by Egaliterrier** [comment]
Using other tools that should be compatible with 4.27.2 also give errors. Tried UUUv4 and cake-san's UE4 base table for CE. Neither work, with the latter maybe pointing in the direction of where things break.
`stringoffset/ByteProperty not found`
`GUObjectArray not found!`
It is trying to find GUObjectArray, but can't. Maybe the engine is a modified version of 4.27.2.

**Comment by Egaliterrier** [comment]
Was just told that the engine is modified as a part of their anti-cheat approach, has anti-debugging and encrypts fname. So I guess fuck modding, right.
