### ISSUE TITLE
[Release] Cannot clone UEPseudo

### ISSUE THREAD

**Issue by pwcarney** [UE4SS-RE/RE-UE4SS#577]
**Branch or Release**
v3.0.1

**Game and Engine Version**
N/A - Build Bug

**Describe the bug**
I am trying to build a repo that uses your repo as a submodule. When I try to run `git submodule update --init --recursive`, your repo fails to clone the submodule `deps/first/Unreal` due to a repository not found error for `git@github.com:Re-UE4SS/UEPseudo.git`. I'm not sure what deps/first/Unreal is supposed to be or why this UEPseudo.git is inaccessible to me. 

**Mods directory**
N/A

**To Reproduce**
1. Clone the repo [here](https://github.com/Procdox/StriveFrameViewer)
2. Run `git submodule update --init --recursive`
3. See error in the terminal

**Expected behavior**
The submodule should clone everything successfully without errors.

**Screenshots, UE4SS Log, and .dmp file**
N/A

**Desktop:**
- OS: Win11

**Additional context**

Here's the console output I see:

PS D:\Git\StriveFrameViewer\RE-UE4SS> git submodule update --init --recursive
Cloning into 'D:/Git/StriveFrameViewer/RE-UE4SS/deps/first/Unreal'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.
fatal: clone of 'git@github.com:Re-UE4SS/UEPseudo.git' into submodule path 'D:/Git/StriveFrameViewer/RE-UE4SS/deps/first/Unreal' failed
Failed to clone 'deps/first/Unreal'. Retry scheduled
Cloning into 'D:/Git/StriveFrameViewer/RE-UE4SS/deps/first/Unreal'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.
fatal: clone of 'git@github.com:Re-UE4SS/UEPseudo.git' into submodule path 'D:/Git/StriveFrameViewer/RE-UE4SS/deps/first/Unreal' failed
Failed to clone 'deps/first/Unreal' a second time, aborting

**Comment by Buckminsterfullerene02** [comment]
The usual answer is to read the build instructions properly which says to join the epic games GitHub organisation so you can clone that submodule, as it is a fork of the unreal engine source code.

However, epic games just did something dumb, where all new users are being sent to a mirror GitHub organisation so therefore does not have access to any forks on the main organisation, such as the UEPseudo repository. You can read more in this forum post: https://forums.unrealengine.com/t/maintenance-on-the-epic-games-github-organization-june-2024/1891135

Currently there is no fix, but for now you could join the UE4SS discord and manually download the package that someone uploaded in #troubleshooting.

**Comment by pwcarney** [comment]
Ah, I noticed I was put into an epic games mirror and assumed that was the cause. Thanks, I was able to download an older build of UEPseudo from the pinned message in the ue4ss-general channel. Specifically I needed UEPseudo-d09b7218bfe7392adeffb500fdeee0b42ca1cd27 because my build was looking for a CMakeLists.txt file within UEPseudo.

**Comment by narknon** [comment]
Reopening until we decide what to do about the mirror.

**Comment by Buckminsterfullerene02** [comment]
This issue is now resolved. Make sure you accept your invite to the original EpicGames org.

![Screenshot_20240627-1106482.png](https://github.com/UE4SS-RE/RE-UE4SS/assets/84156063/4858f0a6-1e29-4c78-862b-099c61c323e0)

**Comment by Jenspi** [comment]
> This issue is now resolved. Make sure you accept your invite to the original EpicGames org.
> 
> ![Screenshot_20240627-1106482.png](https://github.com/UE4SS-RE/RE-UE4SS/assets/84156063/4858f0a6-1e29-4c78-862b-099c61c323e0)

Apologies for commenting on a closed thread, but I just wanted to clarify/expand, for those in the future: the [Epic Games GitHub organization](https://github.com/EpicGames) will have **an invite waiting for you to accept**. Immediately after, you can clone with no issues.
