### ISSUE TITLE
[BUG - Release] BPModloader is stuck due to palworld update

### ISSUE THREAD

**Issue by miku1881** [UE4SS-RE/RE-UE4SS#579]
**Game and Engine Version**
palworld UE4SS 3.0.1

**Describe the bug**
BPModloader is stuck due to palworld update

**Mods directory**
A zip of your Mods folder if you've installed any mods that don't come with UE4SS by default

**To Reproduce**
1. Launch game　 ok
2. Attempt UHT Dump none
3. See error in log 

**Expected behavior**
BPModloader is stuck due to palworld update 

**Screenshots, UE4SS Log, and .dmp file**
If applicable, add screenshots to help explain your problem, and upload the log and .dmp files located in the Win64 directory.

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
BPModloader is stuck due to palworld update 
[UE4SS.log](https://github.com/user-attachments/files/16015677/UE4SS.log)

**Comment by narknon** [comment]
The mods likely need to be updated.

**Comment by miku1881** [comment]
I re-installed it, and I don't get the error like in the log anymore, but the mods in LogicMods and Paks 
in LogicMods and Paks are not loaded.

**Comment by Buckminsterfullerene02** [comment]
Palworld just updated to use IOstore now so any mods that have not been updated to be packaged in that format will not work with UE4SS anymore.

**Comment by AnnznnA** [comment]
Palworld has updated and packaged in chunk, pak mod maybe work again.
