### ISSUE TITLE
[BUG - Release] Can't launch Palworld

### ISSUE THREAD

**Issue by guomz** [UE4SS-RE/RE-UE4SS#581]
**Branch or Release**
palworld UE4SS 3.0.1

**Game and Engine Version**
The latest version of palworld

**Describe the bug**
When I start the game, it will directly report an error and then exit. If I remove all the ue4ss files, it will launch successfully. I haven't installed any mods in the above two situations.

**Mods directory**
\steamapps\common\Palworld\Pal\Binaries\Win64

**To Reproduce**
1. Launch game
2. An error
3. Exit to the desktop

**Expected behavior**
Launch the game successfully.

**Screenshots, UE4SS Log, and .dmp file**
[UEMinidump.dmp](https://github.com/user-attachments/files/16038540/UEMinidump.dmp)
[UE4SS.log](https://github.com/user-attachments/files/16038541/UE4SS.log)
![palworldbug](https://github.com/UE4SS-RE/RE-UE4SS/assets/37978545/d69a3186-c2c6-4ded-a94a-44763a681e0d)

**Desktop (please complete the following information):**
 win10

**Additional context**

**Comment by TerashiofSnagem** [comment]
Having this exact some problem with the exact same error, only the address mentioned is different and seems to change every time I open the game.  Looking forward to a response on how to fix it.

**Comment by geRND90** [comment]
Pal Analyser is broken right now, the UE4SS is working fine..

**Comment by TerashiofSnagem** [comment]
So we're waiting for Palworld to update again?

**Comment by geRND90** [comment]
No.. Waiting for modders update some broken mods like Pal Analyser

**Comment by guomz** [comment]
> No.. Waiting for modders update some broken mods like Pal Analyser. Try open your game with only ue4ss them add other mods one by one, when the game crash you change the mod that causes the crash

I removed all the mods, but it can't launch either.

**Comment by geRND90** [comment]
do a clean install of the game and download the ue4ss files again

**Comment by TerashiofSnagem** [comment]
I did do a clean install before installing the ue4ss files, and... wait...

Last time I checked, I took out all the Binaries/Win64 paks before trying to get the game to run, but I forgot about the .pak mods.

**Comment by TerashiofSnagem** [comment]
Okay, so it was Better Vendors and vux's Faster Mounts that was causing the error.  Without those two mods, the game runs fine.

**Comment by guomz** [comment]
> do a clean install of the game and download the ue4ss files again

thank you, it works.
