### ISSUE TITLE
[BUG - Release] [PS] Scan failed torchlight infinite UE 4.26

### ISSUE THREAD

**Issue by kimsli** [UE4SS-RE/RE-UE4SS#586]
Failed to find GUObjectArray: expected at least one value

Hello, can someone help me fix this problem?

I spent an evening learning about Signatures for GUObjectArray.lua but I didn't understand anything. There is very little information on YouTube about this issue.
I have tried a few tools to get the Address but it is only the offset
gname=0xb9ced40
gobject=0xb9e7988
gworld=0xbb2bb98
I tried every way to switch to signatures but couldn't

Win11

[UE4SS.log](https://github.com/user-attachments/files/16071689/UE4SS.log)

**Comment by narknon** [comment]
We cannot support this game.
