### ISSUE TITLE
[BUG - Experimental] LoadAllAssetsBeforeGeneratingCXXHeaders stuck loading assets

### ISSUE THREAD

**Issue by Buckminsterfullerene02** [UE4SS-RE/RE-UE4SS#605]
**Branch or Release**
commit 86c09a724806609019c4f8af087c452bb3044e56 for DRG
commit 6867a08 for Islands of Insight
have not tried any earlier experimental commits

**Game and Engine Version**
DRG UE4.27
Islands of Insight UE4.27

**Describe the bug**
When `LoadAllAssetsBeforeGeneratingCXXHeaders` is enabled, the CXX dumper gets stuck loading the assets. I tried waiting for 10 minutes and nothing happens. 

Usually, DRG reaches around 4GB of memory usage when loading all assets is complete. However, it seems to now get to around 1.7GB before stopping, freezing UE4SS but game still running fine. My PC has more than enough RAM (over 16GB) to complete this action for both games.

**To Reproduce**
1. Set `LoadAllAssetsBeforeGeneratingCXXHeaders = 1`
2. Attempt CXX dump

**Expected behavior**
Dump to load all assets and finish

**Comment by UE4SS** [comment]
Fixed by https://github.com/Re-UE4SS/UEPseudo/pull/99
