### ISSUE TITLE
[BUG - Release] NotifyOnNewObject not removing callback

### ISSUE THREAD

**Issue by hunterC90** [UE4SS-RE/RE-UE4SS#608]
**Branch or Release**
DEV-UE4SS_v3.0.1

**Game and Engine Version**
Palworld v0.3.4.56710
UE 5.1

**Describe the bug**
`NotifyOnNewObject` should remove its callback when that callback returns true. The callback continues to be executed every time a new object is created.

**Mods directory**
N/A

**Desktop:**
Win10

**To Reproduce**
Run this code from [the docs](https://docs.ue4ss.com/dev/lua-api/global-functions/notifyonnewobject.html) and look at the console when launching the game
```Lua
NotifyOnNewObject("/Script/Engine.Actor", function(ConstructedObject)
    print(string.format("Actor Constructed: %s\n", ConstructedObject:GetFullName()))

    -- Unregister this callback after the first actor is found,
    -- meaning this current function will only be called exactly once
    return true
end)
```

On launch, I see in the console
```[22:43:46] Event loop start
[22:43:46] [Lua] Actor Constructed: BP_Player_ForUI_C /Game/Pal/Blueprint/UI/SceneCaptureWidget/BP_PalPlayerCaptureSet.BP_PalPlayerCaptureSet_C:ChildActor_GEN_VARIABLE.ChildActor_GEN_VARIABLE_BP_Player_ForUI_C_CAT
[22:43:46] [Lua] Actor Constructed: BP_PalWorldSettings_C /Temp/Untitled_0.Untitled:PersistentLevel.BP_PalWorldSettings_C
[22:43:46] [Lua] Actor Constructed: BuoyancyManager /Temp/Untitled_0.Untitled:PersistentLevel.BuoyancyManager_2147482517
...
```
And about 2 dozen more 

**Additional context**
Also worth noting, the docstring and type annotations for `NotifyOnNewObject` in Types.lua make no indication that I should be able to stop additional callbacks where the docs page says I should

From Types.lua
```Lua
---Executes the provided Lua function whenever an instance of the provided class is constructed.
---Inheritance is taken into account, so if you provide "/Script/Engine.Actor" as the class then it will execute your
---Lua function when any object is constructed that's either an AActor or is derived from AActor.
---@param UClassName string
---@param Callback fun()
function NotifyOnNewObject(UClassName, Callback) end
```

From the docs

> Callback Return Value
\# | Type | Information
1 | boolean | If true, remove the current callback from listening to any more notifications

**Comment by UE4SS** [comment]
You're using the dev docs, which is only accurate for the next release of UE4SS.
This feature is part of the next version of UE4SS which has not yet been officially released.
You can find experimental builds of this version here: https://github.com/UE4SS-RE/RE-UE4SS/releases/tag/experimental
Scroll down to assets, and keep scrolling until you find a recent date.
Use the [non-dev](https://docs.ue4ss.com/lua-api/global-functions/notifyonnewobject.html) docs instead if your mod is targeting the current release of UE4SS.
