### ISSUE TITLE
[BUG - Release] Hook Function Error

### ISSUE THREAD

**Issue by nieboczek** [UE4SS-RE/RE-UE4SS#621]
**Branch or Release**
3.0.1 (zDEV)

**Game and Engine Version**
Grocery Store Simulator - UE 5.2.1.0

**Describe the bug**
When a hook is triggered, even when the hook is empty it errors:
```
[07:44:00] Error: [push_textproperty] Operation::GetParam is not supported
No traceback
[07:44:00] Error: [push_textproperty] Operation::GetParam is not supported
No traceback
```

**Mods directory**
[Mods.zip](https://github.com/user-attachments/files/16634529/Mods.zip)

**To Reproduce**
1. Launch Grocery Store Simulator
2. Click the New Game or Continue
3. Open computer
4. Go to the "ORDER GOODS" tab
5. Add any item to cart

**Expected behavior**
Hook function doesn't error

**Screenshots, UE4SS Log, and .dmp file**
[UE4SS.log](https://github.com/user-attachments/files/16634535/UE4SS.log)

**Desktop (please complete the following information):**
 - OS: Win11

**Additional context**
The hook is in the NoOrderLimit mod.

**Comment by nexustheru** [comment]
have you checked the permit on writing files in windows,games needs pemission, i did google this aswell bc its not common, what i seems to tho,u might need to update a few softwares, and this includes this engines 2 and 3 software usabillity according to the games your using, this link is a wildcard but https://stackoverflow.com/questions/60769220/typeerror-props-navigation-getparam-is-not-a-function-inprops-navigation-get it might get a hint where programming is wrong. im not even sure if its related tho i never heard this error before.

**Comment by nexustheru** [comment]
update the dependent software, bc it is function that is not yet suported, i dont know what verions but  urec missing functions getparam, update and download any missing 3 and 2 third libraries, put it right and it should work.

**Comment by nieboczek** [comment]
That doesn't really help me

**Comment by nieboczek** [comment]
Works on experimental
