### ISSUE TITLE
[BUG - BlackMythWukong ]Unable to load blueprint mod

### ISSUE THREAD

**Issue by EAZENLEE** [UE4SS-RE/RE-UE4SS#637]
**Branch or Release**
The Tag for the Release you are using, or the commit you used if you built from source yourself.
https://www.nexusmods.com/blackmythwukong/mods/19

**Game and Engine Version**
Game where the bug occurred, and the UE engine version of the game.
Game: Black Myth Wukong
UE engine: https://github.com/kboykboy2/UnrealEngine/

**Describe the bug**
Unable to load the blueprint mod packaged by this engine

**Mods directory**
A zip of your Mods folder if you've installed any mods that don't come with UE4SS by default

**To Reproduce**
1. Launch game
2. Attempt UHT Dump
3. See error in log

**Expected behavior**

**Screenshots, UE4SS Log, and .dmp file**
If applicable, add screenshots to help explain your problem, and upload the log and .dmp files located in the Win64 directory.
[error.txt](https://github.com/user-attachments/files/16770662/error.txt)
![image](https://github.com/user-attachments/assets/005eaf02-f055-4ff1-bf54-e4a4ae84d3b1)

**Desktop (please complete the following information):**
 - OS: [e.g. Win10, Win11]
W11 64x

**Additional context**

**Comment by narknon** [comment]
This is unrelated to the base UE4SS repo and likely user error in packaging.

**Comment by EAZENLEE** [comment]
> This is unrelated to the base UE4SS repo and likely user error in packaging.

Is this an engine issue or a project issue? The packaging settings are the same as using the official engine and project normally

**Comment by inkydragon** [comment]
> This is unrelated to the base UE4SS repo and likely user error in packaging.

The error comes from the packing process.
But here's how we could improve the error message when `AssetData` is nil.

https://github.com/UE4SS-RE/RE-UE4SS/blob/e123730ef514e7e65698881e5f7124d43e3ff94f/assets/Mods/BPModLoaderMod/Scripts/main.lua#L210-L213

**Comment by narknon** [comment]
Yes, the error message is a leftover from the old script that I forgot to fix.  Regardless, this discussion should not be happening on this repo, it should be on nexus.
