### ISSUE TITLE
[BUG - Experiemental] OpenGL3 backend white screen  

### ISSUE THREAD

**Issue by Lioncky** [UE4SS-RE/RE-UE4SS#642]
*Like #361 Opengl Backend Crash*

**Screenshots, UE4SS Log, and .dmp file**
![image](https://github.com/user-attachments/assets/c19aea90-fb06-4f50-8136-92924cddc246)

**Desktop (please complete the following information):**
Win11 

* GAME *
BlackMyth(UE5.0).

**Additional context**
Maybe some one could fix it because opengl's low performance is better than dx11.
So even if dx11 is work well, I prefer to use opengl.
I have alreary build the latest UE4SS the bug still apper.

**config**
> only relative was upload, other is unnecessary
```c
[Debug]
; Whether to enable the external UE4SS debug console.
ConsoleEnabled = 1
GuiConsoleEnabled = 1
GuiConsoleVisible = 1

; Multiplier for Font Size within the Debug Gui
; Default: 1
GuiConsoleFontScaling = 1.6

; The API that will be used to render the GUI debug window.
; Valid values (case-insensitive): dx11, d3d11, opengl
; Default: opengl
GraphicsAPI = opengl

[Hooks]
HookProcessInternal = 1
HookProcessLocalScriptFunction = 1
HookInitGameState = 1
HookLoadMap = 1
HookCallFunctionByNameWithArguments = 1
HookBeginPlay  = 1
HookLocalPlayerExec = 1
HookAActorTick = 1
FExecVTableOffsetInLocalPlayer = 0x28

[ExperimentalFeatures]
; Only enable these features if you know what you are doing.
GUIUFunctionCaller = 0

```
> Have tested with latest release, latest clone bunch.

**Comment by Lioncky** [comment]
Tested the window won't flush while resize, seems glfwSwapBuffers not work.
I append glFlush() after it still no effect. glfwSwapBuffers will call FreeLibrary(OpenGL.dll).
![image](https://github.com/user-attachments/assets/8c89c9cb-5111-4a73-b884-45ce8d0a5fb6)

**Comment by narknon** [comment]
This is due to the dwmapi.dll being used on the runner not matching the exports on the local.  Will likely be fixed soon.

**Comment by Lioncky** [comment]
Sounds great, I've made an opengl library and inject successful, I checked your code and found every thing is ok, so that make me confused.

> This is due to the dwmapi.dll being used on the runner not matching the exports on the local. Will likely be fixed soon.
I check it now... You're right, it works well now.
![image](https://github.com/user-attachments/assets/4316e8f0-acf7-4723-a275-106aacb52652)

**Comment by Lioncky** [comment]
By the way, the glwindow with 4K(3840*2160) shows too small, better get a suitable scale. ImguiBackend has a scale function.

**Comment by mitchell-merry** [comment]
Hi, I don't think this issue should be closed? This is present on 3.0.1, and I don't know how to fix it.

This line:
> This is due to the dwmapi.dll being used on the runner not matching the exports on the local. Will likely be fixed soon.

doesn't mean anything to me, unfortunately.

**Comment by demiacle** [comment]
I see this is closed, but I ran into this issue and google directed me here. Opting out of opengl got me working. Try...

GraphicsAPI = dx11

For those who come after

**Comment by UE4SS** [comment]
> I see this is closed, but I ran into this issue and google directed me here. Opting out of opengl got me working. Try...
> 
> GraphicsAPI = dx11
> 
> For those who come after

Or try a newer version of UE4SS.
