### ISSUE TITLE
[UNREAL ENGINE] How can i make custom Unreal Engine for game?

### ISSUE THREAD

**Issue by NyanAlex** [UE4SS-RE/RE-UE4SS#643]
I want to make a mod for a game that uses its custom unreal engine, are there any tutorials how to make it?

**Comment by Ledahvu** [comment]
I think we need to understand how to make games with unreal engine. Use that knowledge to create mods for the game. As for contributing pak files it is very easy. I'm also learning about how to make game mods for TCSM but have not had any results yet.

**Comment by Ledahvu** [comment]
If possible I think you should create a channel and find like-minded people to discuss more about the issue of game hacking.

**Comment by NyanAlex** [comment]
> I think we need to understand how to make games with unreal engine. Use that knowledge to create mods for the game. As for contributing pak files it is very easy. I'm also learning about how to make game mods for TCSM but have not had any results yet.

Modding for online games not allowed here, so i asking about all games with custom Unreal Engine

**Comment by Buckminsterfullerene02** [comment]
This is not the appropriate place to ask such questions. Perhaps you will be better served to ask in the [unreal engine modding discord](https://discord.gg/unreal-engine-modding-876613187204685934)?
