### ISSUE TITLE
[BUG - Release]ue 5.4

### ISSUE THREAD

**Issue by T0PGlitch3r** [UE4SS-RE/RE-UE4SS#654]
The UE4SS needs updating so it can support version 5.4 as for now you get an error

**Comment by Ekirou** [comment]
need 5.4 support

**Comment by UE4SS** [comment]
It's supported in the experimental release for now, and eventually there will be an official release.
Here: https://github.com/UE4SS-RE/RE-UE4SS/releases/download/experimental/UE4SS_v3.0.1-175-g82b2ebf.zip

**Comment by igromanru** [comment]
The latest experimental release which should have 5.4 FText signature is actually: https://github.com/UE4SS-RE/RE-UE4SS/releases/download/experimental/UE4SS_v3.0.1-174-g501c669.zip
