### ISSUE TITLE
[BUG - Release] Not working with latest update of Palworld

### ISSUE THREAD

**Issue by Opusdeus** [UE4SS-RE/RE-UE4SS#658]
Version 3.0.1 of UE4SS

Game Version: v0.3.7 on Steam

Error Name:
LoginId:93fbd4d049c968cb2e22239890fc1335
EpicAccountId:cbc849d1771e4c14a656731aca969687

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0xffffffffffffffff

Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
Palworld_Win64_Shipping
kernel32
ntdll

I launched the game and tried to go into a world then it crashed. I thought it was my other mods so I deleted the ones that weren't updated yet by the creator and downloaded the updated version of the ones that were updated by their creators, however, that didn't fix anything. I uninstalled Palworld then reinstalled it, but that didn't work either. I am using Windows 10 and the UE4SS file is located in the area where the instructions told me to put it. Everything was working fine prior to the update.

**Comment by AnnznnA** [comment]
Maybe you need to try to remove all mods into the game first

If it's an exception of ue4ss, the top of the stack won't be Palworld_Win64_Shipping,
It is possible that the code of some mod mods modifies the values in the game and causes the game to have uncaught exceptions, I have such experience, and this is not something that can be solved by UE4SS source code modification, and it is up to the mod author to understand Palworld's object use himself,Just like the loadermap will inherit the slot array of the holder component of the previous map, if I customize them, I will get an error

**Comment by Opusdeus** [comment]
Everything was working fine prior to v0.3.7. They said that they reduced memory consumption throughout the game so maybe that has something to do with it? I doubt it does, but I'm kind of spit-balling due to me trying everything I've been told to do to fix it. I even uninstalled every mod and manually reinstalled them one by one, booting up the game each time, just to see if there was a specific mod causing it, but that didn't do anything because the game crashed anyway even with skin mods. I updated my Nvidia GPU drivers, followed tutorials, opened the Nvidia Control Panel and tried to fix it like that, and ran the game in Admin mode but to no avail. I'm stumped.

**Comment by igromanru** [comment]
You haven't posted the UE4SS.log nor the crash dump.
If you don't have already, download the zDEV version of UE4SS and use **UE4SS.dll** and **UE4SS.pdb** from there.
Then start the game, bundle the **UE4SS.log** together with crash dump into a zip file, then post it here.  
The information you posted so far is useless.

**Comment by Opusdeus** [comment]
[CrashDump.zip](https://github.com/user-attachments/files/17111539/CrashDump.zip)
Like this?

**Comment by AnnznnA** [comment]
> [CrashDump.zip](https://github.com/user-attachments/files/17111539/CrashDump.zip) Like this?

This dmp file is not from ue4ss and may not reveal any other issues.

As for the provided log information, it can be seen that the game does not crash immediately after opening. You have installed many mods, and the mods cause crashes while ue4ss cannot record dmp. Often, this is due to unreasonable code modifying the game's internal values, resulting in unprocessed exceptions in the game's internal calls

To rule out the issue with ue4ss, you can uninstall all mods first and then test. I have been conducting [Live View] testing on ue4ss for a long time in version 3.7, and it has been running stably for palworld

**Comment by igromanru** [comment]
I see some Blueprint mods in the log. Some of them are probably outdated.  
I don't know about Blueprint mods error handing, if it can crash the game. In Lua you would just get an error if a property that you try to access doesn't exist anymore.  
I would look what authors of the mods you use have to say.  
Overall, like AnnznnA said already, disable the mods one by one and see when the game stop crashing.

**Comment by Opusdeus** [comment]
I figured out what was wrong.
