### ISSUE TITLE
Blueprint mod material issue

### ISSUE THREAD

**Issue by xaj666** [UE4SS-RE/RE-UE4SS#691]
I would like to ask how to load custom materials in Blueprint mod. The objects I generate using Blueprint mod do not have materials

**Comment by ErickCHIN000** [comment]
Im trying to get in to bp modding but im having some issues, could you point me to some resources?

i followed both of these but i just cant seem to get it to work
https://www.youtube.com/watch?v=fB3yT85XhVA&t=1620s
https://www.youtube.com/watch?v=6MUkUFhumo8&t=191s

**Comment by Buckminsterfullerene02** [comment]
https://github.com/Dmgvol/UE_Modding
