### ISSUE TITLE
Dakar Desert Rally Startup Crash

### ISSUE THREAD

**Issue by timothycolangelo** [UE4SS-RE/RE-UE4SS#693]
**Branch or Release**
v.3.0.1

**Game and Engine Version**
Dakar Desert Rally, UE 4.27.2.0
**Describe the bug**
The game crashes at start-up. I tried to use U4ESS to mod the game, I have not made any modifications to it for the time being.

**Mods directory**
N/A

**To Reproduce**
1. Enable console
2. Launch game
3. Fatal error pop-up

**Expected behavior**
I expected the game to run normally.

**Screenshots, UE4SS Log, and .dmp file**
![image](https://github.com/user-attachments/assets/674b8632-f418-4d3e-9f71-9866dec9c989)

[UE4SS.log](https://github.com/user-attachments/files/17486901/UE4SS.log)
[UE4SS_ObjectDump.txt](https://github.com/user-attachments/files/17486907/UE4SS_ObjectDump.txt)

**Desktop (please complete the following information):**
-OS: Win11

**Additional context**
No further context. The game has never been datamined and/or modded.

**Comment by timothycolangelo** [comment]
I re-added the Mods folder, same result.

**Comment by Arturo83** [comment]
Same issue here. UE4SS was already working with older Dakar versions last year but not with the latest Dakar update 2.2 and 2.3.
Fatat error appears even you set all MODS to 0 and console to 0.
I tried today the latest experimental version UE4SS_v3.0.1-201-g7cd4e3f.

**Comment by Arturo83** [comment]
I found a wokaround to bypass UE4SS to crash the game "fatal error":

Open UE4SS-settings.ini and change the following Hooks paramaters to 0

[Hooks]
HookInitGameState = 0
HookLoadMap = 0

All the other hooks = 1

Now start the game. 
You can use at least UE5 Console for console commands, Live View and Dumpings. 
Unfortunately, the deactivated Hooks are required to spawn ModActor.
I have no idea how to make these Hooks working. 
I think an expert has to create signatures for InitGameState and LoadMap based on their memory locations and patterns.

Dumper-7 is a tool used for reverse engineering Unreal Engine games, primarily focused on dumping game assets, memory structures, and function signatures. It helps to extract useful information for modding or debugging games built on Unreal Engine.

AOB Scanning in Cheat Engine can identify patterns for function calls or memory locations related to InitGameState and LoadMap, which Dumper-7 might not provide out-of-the-box (output file attached).
Cheat Engine or tools like IDA Pro help find exact memory patterns (AOBs) that UE4SS can use to hook functions reliably.

[DUMPER-7_OUTPUT_for_Dakar2Game.zip](https://github.com/user-attachments/files/17936174/DUMPER-7_OUTPUT_for_Dakar2Game.zip)

**Comment by UE4SS** [comment]
This is likely a VTable problem.

**Comment by Arturo83** [comment]
I tested the latest UE4SS experimental version 3.0.1-228
The game crashes always the the same point "DKCheatManager", which is visible in LiveView
Screenshot
<img width="622" alt="image" src="https://github.com/user-attachments/assets/8a570ec4-6144-4743-b171-8c0879225e16" />

**Comment by narknon** [comment]
Online PVP?

**Comment by UE4SS** [comment]
> Online PVP?

It appears to be a racing game with both singleplayer and multiplayer components.
