### ISSUE TITLE
Does not work with Hogwarts Legacy

### ISSUE THREAD

**Issue by DominikCGI** [UE4SS-RE/RE-UE4SS#702]
Installing this does nothing. It does not work at all. Mods don't load. F10 does not open a console. Is this even updated? Has this even ever been functional? If so, please tell us how, because the descriptiuon you have is useless

**Comment by narknon** [comment]
Your issue report does nothing. It tells us nothing at all. The description of the problem you have is useless.

**Comment by DominikCGI** [comment]
How do I install it? I have download all files and placed them in my steam game folder
It does not work. Why can't you just tell people how to install it? What do I need to do to make it work?
