### ISSUE TITLE
When is the Unreal Engine 4/5 Scripting System expected to support Linux?

### ISSUE THREAD

**Issue by fanhao99** [UE4SS-RE/RE-UE4SS#707]
When is the Unreal Engine 4/5 Scripting System expected to support Linux?

**Comment by Buckminsterfullerene02** [comment]
When our volunteer contributors have time to continue work on our [Linux port](https://github.com/UE4SS-RE/RE-UE4SS/pull/384)

**Comment by UE4SS** [comment]
Issue already exists: #364
