### ISSUE TITLE
reoccurring fatal error

### ISSUE THREAD

**Issue by vortgin** [UE4SS-RE/RE-UE4SS#735]
ver. 3.0.1-201-g7cd4e3f
for Hogwarts legacy on steam on Win 11
Im running mods through vortex 

When the game loads I get a fatal crash error and a dmp file. I originally thought that it was a missing file from a deleted mod. But I uninstalled and reinstalled everything from the base game, save data, and mods and was still getting it. It only stopped when i disabled UE4SS

(I dont know how to attach my mod folder its 183mb compressed sry)
Mods list (all from nexus)
Ascendio III https://www.nexusmods.com/hogwartslegacy/mods/69
Autohomora https://www.nexusmods.com/hogwartslegacy/mods/297
Black Nail Polish https://www.nexusmods.com/hogwartslegacy/mods/261
Even Brighter Eyes https://www.nexusmods.com/hogwartslegacy/mods/1058
RE-UE4SS for Hogwarts Legacy https://www.nexusmods.com/hogwartslegacy/mods/942
Silencio - Floo Lady Silencer https://www.nexusmods.com/hogwartslegacy/mods/95

the mod I originally uninstalled
Spells Enhanced - With Voice Lines https://www.nexusmods.com/hogwartslegacy/mods/1325

[crash_2024_12_29_23_22_03.zip](https://github.com/user-attachments/files/18271281/crash_2024_12_29_23_22_03.zip)
[UE4SS.log](https://github.com/user-attachments/files/18271345/UE4SS.log)

**Comment by UE4SS** [comment]
Add UE4SS.log please.

**Comment by vortgin** [comment]
[UE4SS.log](https://github.com/user-attachments/files/18271344/UE4SS.log)
forgot this sry

**Comment by UE4SS** [comment]
Try disable all your mods, AND all the built-in mods and see if it still crashes.

**Comment by vortgin** [comment]
the game by its self runs. i even tested the mods one by one (except Autohomora since it needs UE4SS) every thing else works fine

**Comment by UE4SS** [comment]
> the game by its self runs. i even tested the mods one by one (except Autohomora since it needs UE4SS) every thing else works fine

Yes but have you tried leaving UE4SS installed, but with all UE4SS mods off ?
We need to know if this is a problem with a mod (including our own) or UE4SS itself.

**Comment by vortgin** [comment]
by its-self UE4SS isn't crashing

**Comment by UE4SS** [comment]
> by itself UE4SS isn't crashing

Can you enable each mod one by one to narrow down which mod is causing the problem ?

**Comment by vortgin** [comment]
all the lua mods are working

**Comment by vortgin** [comment]
im an idiot its autohomora, i never tested it and the game crashes as soon as it loads

**Comment by igromanru** [comment]
I'm currently maintaining [RE-UE4SS for Hogwarts Legacy](https://www.nexusmods.com/hogwartslegacy/mods/942) on Nexus and from 7k downloads of the working version that I have uploaded, only few people commented that their game crash. It's always the same UE4SS mods which depend on other mods which are Blueprint mods and most likely outdated. 
Any issues here complaining about UE4SS in Hogwarts Legacy can be closed immediately.
