### ISSUE TITLE
[BUG - Release]

### ISSUE THREAD

**Issue by pondwater** [UE4SS-RE/RE-UE4SS#736]
**Branch or Release** v3.01
The Tag for the Release you are using, or the commit you used if you built from source yourself.

**Game and Engine Version**
 palworld

**Describe the bug** 
added this to the palworld server and when logging back in from a player account makes player create a new profile, if removing this and restarting the server player now loads into the correct profile

**Mods directory**
 just the default mods that come in the zip folder

**Desktop (please complete the following information):**
 - OS: [e.g. Win10, Win11] trunas scale/ running a docker with palworld server running with WINE
 - ripps818/docker-palworld-dedicated-server-wine

**Additional context**

**Comment by narknon** [comment]
Duplicate issue.

**Comment by pondwater** [comment]
wheres te other thread so i can follow, sorry
