### ISSUE TITLE
Not compatible with Returnal?

### ISSUE THREAD

**Issue by BurgersMcFly** [UE4SS-RE/RE-UE4SS#85]
Keep getting this error with Returnal no matter what I do (https://store.steampowered.com/app/1649240/Returnal/). D:

Used the CustomGameConfigs for it. Even tried setting its Engine version in settings.ini although not sure if I've done it correctly (MajorVersion: 4.25.1.0/MinorVersion: 4.25.1.0). Pretty sure I've done everything else correctly. I've already got it working with Hogwarts Legacy and I'm loving it. Even made some mods with it and there are a lot of things I'd like to experiment with in Returnal.

[2023-03-11 04:45:20] StaticConstructObject_Internal address: 0x7ffa8db3cc60 <- Built-in
[2023-03-11 04:45:20] Scan attempt 2000/2000
[2023-03-11 04:45:20] FName::ToString address: 0x7ffa8dea7b30 <- Lua Script
[2023-03-11 04:45:20] AOB scans could not be completed because of the following reasons:
Was unable to find AOB for 'Unreal Engine Version'.
Could not determine Unreal Engine version: 'Branch' member variable FString data was nullptr
You need to override the engine version in 'UE4SS-settings.ini.

[2023-03-11 04:45:20] StaticConstructObject_Internal address: 0x7ffa8db3cc60 <- Built-in
[2023-03-11 04:45:20] Fatal Error: AOB scans could not be completed because of the following reasons:
Was unable to find AOB for 'Unreal Engine Version'.
Could not determine Unreal Engine version: 'Branch' member variable FString data was nullptr
You need to override the engine version in 'UE4SS-settings.ini.

**Comment by UE4SS** [comment]
>Fatal Error: AOB scans could not be completed because of the following reasons: Was unable to find AOB for 'Unreal Engine Version'. Could not determine Unreal Engine version: 'Branch' member variable FString data was nullptr **You need to override the engine version in 'UE4SS-settings.ini**.

Try manually setting the engine version like it says to do in the error message.
The engine version can usually be found by right clicking the Win64-Shipping.exe, clicking properties, and going to the "Details" tab.

**Comment by BurgersMcFly** [comment]
Yep, figured out how to set it up correctly. Thanks mate!
