### ISSUE TITLE
Do you have any plans to make it compatible with Linux/Android?[BUG - Release]

### ISSUE THREAD

**Issue by lpcdma** [UE4SS-RE/RE-UE4SS#87]
I have tried to make it compatible with Android, but dealing with wchar_t and wstring is very painful. In *nix systems, wchar_t is 4 bytes, while the UE engine actually uses char16_t which is 2 bytes. If there are any compatibility plans, please pay attention to this detail.

**Comment by narknon** [comment]
Linux through wine may be possible.  Android there's no chance.
